// examples/vue-showcase/src/pages/ApiCallPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { providePulse } from '@pulse/vue'
import { engine } from '../../../vue/api-call/src/engine'
import ApiCallApp from '../../../vue/api-call/src/App.vue'

providePulse(engine)

onMounted(() => {
  ;(window as any).__pulseEngine = engine
})
onUnmounted(() => {
  ;(window as any).__pulseEngine = null
})
</script>

<template>
  <ApiCallApp />
</template>

// examples/react-showcase/src/pages/ApiCallPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/api-call/src/engine'
import ApiCallApp from '../../../react/api-call/src/App'

export default function ApiCallPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <ApiCallApp />
    </PulseProvider>
  )
}
