// examples/vue-showcase/src/pages/CanvasPaintPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { providePulse } from '@pulse/vue'
import { engine } from '../../../vue/canvas-paint/src/engine'
import App from '../../../vue/canvas-paint/src/App.vue'

providePulse(engine)

onMounted(() => {
  ;(window as any).__pulseEngine = engine
})
onUnmounted(() => {
  ;(window as any).__pulseEngine = null
})
</script>

<template>
  <App />
</template>

// examples/react-showcase/src/pages/CanvasPaintPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/canvas-paint/src/engine'
import CanvasPaintApp from '../../../react/canvas-paint/src/App'

export default function CanvasPaintPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <CanvasPaintApp />
    </PulseProvider>
  )
}
