// examples/solid-showcase/src/pages/DragApiAnimationPage.tsx
import { onMount, onCleanup } from 'solid-js'
import { PulseProvider } from '@pulse/solid'
import { engine } from '../../../solid/drag-api-animation/src/engine'
import DragApiAnimationApp from '../../../solid/drag-api-animation/src/App'

export default function DragApiAnimationPage() {
  onMount(() => {
    ;(window as any).__pulseEngine = engine
  })
  onCleanup(() => {
    ;(window as any).__pulseEngine = null
  })

  return (
    <PulseProvider engine={engine}>
      <div class="example-container" style={{ 'min-height': '100%' }}>
        <DragApiAnimationApp />
      </div>
    </PulseProvider>
  )
}

// examples/react-showcase/src/pages/DragApiAnimationPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/drag-api-animation/src/engine'
import DragApiAnimationApp from '../../../react/drag-api-animation/src/App'

export default function DragApiAnimationPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <DragApiAnimationApp />
    </PulseProvider>
  )
}
