// examples/solid-showcase/src/pages/FormWizardPage.tsx
import { onMount, onCleanup } from 'solid-js'
import { PulseProvider } from '@pulse/solid'
import { engine } from '../../../solid/form-wizard/src/engine'
import FormWizardApp from '../../../solid/form-wizard/src/App'

export default function FormWizardPage() {
  onMount(() => {
    ;(window as any).__pulseEngine = engine
  })
  onCleanup(() => {
    ;(window as any).__pulseEngine = null
  })

  return (
    <PulseProvider engine={engine}>
      <div class="example-container" style={{ 'min-height': '100%' }}>
        <FormWizardApp />
      </div>
    </PulseProvider>
  )
}

// examples/react-showcase/src/pages/FormWizardPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/form-wizard/src/engine'
import FormWizardApp from '../../../react/form-wizard/src/App'

export default function FormWizardPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <FormWizardApp />
    </PulseProvider>
  )
}
