// examples/vue-showcase/src/pages/MorphingGrid3DPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { providePulse } from '@pulse/vue'
import { engine } from '../../../vue/3d-morphing-grid/src/engine'
import App from '../../../vue/3d-morphing-grid/src/App.vue'

providePulse(engine)

onMounted(() => {
  ;(window as any).__pulseEngine = engine
})
onUnmounted(() => {
  ;(window as any).__pulseEngine = null
})
</script>

<template>
  <App />
</template>

// examples/react-showcase/src/pages/MorphingGrid3DPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/3d-morphing-grid/src/engine'
import MorphingGrid3DApp from '../../../react/3d-morphing-grid/src/App'

export default function MorphingGrid3DPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <MorphingGrid3DApp />
    </PulseProvider>
  )
}
