// examples/vue-showcase/src/pages/SimpleAnimationPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { providePulse } from '@pulse/vue'
import { engine } from '../../../vue/simple-animation/src/engine'
import SimpleAnimationApp from '../../../vue/simple-animation/src/App.vue'

providePulse(engine)

onMounted(() => {
  ;(window as any).__pulseEngine = engine
})
onUnmounted(() => {
  ;(window as any).__pulseEngine = null
})
</script>

<template>
  <SimpleAnimationApp />
</template>

// examples/react-showcase/src/pages/SimpleAnimationPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/simple-animation/src/engine'
import SimpleAnimationApp from '../../../react/simple-animation/src/App'

export default function SimpleAnimationPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <SimpleAnimationApp />
    </PulseProvider>
  )
}
