// examples/react-showcase/src/pages/DragApiAnimationPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/drag-api-animation/src/engine'
import DragApiAnimationApp from '../../../react/drag-api-animation/src/App'

export default function DragApiAnimationPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <DragApiAnimationApp />
    </PulseProvider>
  )
}

// examples/vue-showcase/src/pages/DragApiAnimationPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { providePulse } from '@pulse/vue'
import { engine } from '../../../vue/drag-api-animation/src/engine'
import DragApiAnimationApp from '../../../vue/drag-api-animation/src/App.vue'

providePulse(engine)

onMounted(() => {
  ;(window as any).__pulseEngine = engine
})
onUnmounted(() => {
  ;(window as any).__pulseEngine = null
})
</script>

<template>
  <DragApiAnimationApp />
</template>
