// examples/react-showcase/src/pages/FormWizardPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/form-wizard/src/engine'
import FormWizardApp from '../../../react/form-wizard/src/App'

export default function FormWizardPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <FormWizardApp />
    </PulseProvider>
  )
}

// examples/vue-showcase/src/pages/FormWizardPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { providePulse } from '@pulse/vue'
import { engine } from '../../../vue/form-wizard/src/engine'
import FormWizardApp from '../../../vue/form-wizard/src/App.vue'

providePulse(engine)

onMounted(() => {
  ;(window as any).__pulseEngine = engine
})
onUnmounted(() => {
  ;(window as any).__pulseEngine = null
})
</script>

<template>
  <FormWizardApp />
</template>
