// examples/react-showcase/src/pages/GanttChartPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/gantt-chart/src/engine'
import GanttChartApp from '../../../react/gantt-chart/src/App'

export default function GanttChartPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <GanttChartApp />
    </PulseProvider>
  )
}

// examples/vue-showcase/src/pages/GanttChartPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { providePulse } from '@pulse/vue'
import { engine } from '../../../vue/gantt-chart/src/engine'
import App from '../../../vue/gantt-chart/src/App.vue'

providePulse(engine)

onMounted(() => {
  ;(window as any).__pulseEngine = engine
})
onUnmounted(() => {
  ;(window as any).__pulseEngine = null
})
</script>

<template>
  <App />
</template>
