// examples/react-showcase/src/pages/ImageFiltersPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/image-filters/src/engine'
import ImageFiltersApp from '../../../react/image-filters/src/App'

export default function ImageFiltersPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <ImageFiltersApp />
    </PulseProvider>
  )
}

// examples/vue-showcase/src/pages/ImageFiltersPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { providePulse } from '@pulse/vue'
import { engine } from '../../../vue/image-filters/src/engine'
import App from '../../../vue/image-filters/src/App.vue'

providePulse(engine)

onMounted(() => {
  ;(window as any).__pulseEngine = engine
})
onUnmounted(() => {
  ;(window as any).__pulseEngine = null
})
</script>

<template>
  <App />
</template>
