// examples/react-showcase/src/pages/RealtimeDashboardPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/realtime-dashboard/src/engine'
import RealtimeDashboardApp from '../../../react/realtime-dashboard/src/App'

export default function RealtimeDashboardPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <RealtimeDashboardApp />
    </PulseProvider>
  )
}

// examples/vue-showcase/src/pages/RealtimeDashboardPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { providePulse } from '@pulse/vue'
import { engine } from '../../../vue/realtime-dashboard/src/engine'
import RealtimeDashboardApp from '../../../vue/realtime-dashboard/src/App.vue'

providePulse(engine)

onMounted(() => {
  ;(window as any).__pulseEngine = engine
})
onUnmounted(() => {
  ;(window as any).__pulseEngine = null
})
</script>

<template>
  <RealtimeDashboardApp />
</template>
