// examples/react-showcase/src/pages/TodoListPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/todo-list/src/engine'
import TodoListApp from '../../../react/todo-list/src/App'

export default function TodoListPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <TodoListApp />
    </PulseProvider>
  )
}

// examples/vue-showcase/src/pages/TodoListPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { providePulse } from '@pulse/vue'
import { engine } from '../../../vue/todo-list/src/engine'
import TodoApp from '../../../vue/todo-list/src/App.vue'

providePulse(engine)

onMounted(() => {
  ;(window as any).__pulseEngine = engine
})
onUnmounted(() => {
  ;(window as any).__pulseEngine = null
})
</script>

<template>
  <TodoApp />
</template>
