// examples/react/data-table/src/App.js
import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { useSignal, useEmit } from '@pulse/react';
import { useCallback, useRef } from 'react';
import { sortState, filters, currentPage, pageSize, selectedRows, expandedRows, searchQuery, columnWidths, isLoading, SortChanged, FilterChanged, PageChanged, RowSelected, RowExpanded, BulkAction, SearchChanged, ColumnResized, SelectAll, DeselectAll, getProcessedData, } from './engine';
// ---------------------------------------------------------------------------
// Status badge
// ---------------------------------------------------------------------------
function StatusBadge({ status }) {
    const colors = {
        Active: { bg: 'rgba(34, 197, 94, 0.15)', text: '#4ade80' },
        Inactive: { bg: 'rgba(239, 68, 68, 0.15)', text: '#f87171' },
        Pending: { bg: 'rgba(245, 158, 11, 0.15)', text: '#fbbf24' },
    };
    const c = colors[status] || { bg: '#334155', text: '#94a3b8' };
    return (_jsx("span", { style: {
            padding: '2px 8px',
            borderRadius: 10,
            background: c.bg,
            color: c.text,
            fontSize: 11,
            fontWeight: 600,
        }, children: status }));
}
// ---------------------------------------------------------------------------
// Highlight matching text
// ---------------------------------------------------------------------------
function HighlightText({ text, query }) {
    if (!query)
        return _jsx(_Fragment, { children: text });
    const idx = text.toLowerCase().indexOf(query.toLowerCase());
    if (idx === -1)
        return _jsx(_Fragment, { children: text });
    return (_jsxs(_Fragment, { children: [text.slice(0, idx), _jsx("span", { style: { background: '#fbbf2440', color: '#fbbf24', borderRadius: 2, padding: '0 1px' }, children: text.slice(idx, idx + query.length) }), text.slice(idx + query.length)] }));
}
// ---------------------------------------------------------------------------
// Column header with sort
// ---------------------------------------------------------------------------
function SortHeader({ label, column, width, }) {
    const emit = useEmit();
    const sort = useSignal(sortState);
    const widths = useSignal(columnWidths);
    const resizing = useRef(false);
    const startX = useRef(0);
    const startWidth = useRef(0);
    const isActive = sort.column === column;
    const direction = isActive ? sort.direction : null;
    const handleSort = useCallback(() => {
        let newDir;
        if (!isActive) {
            newDir = 'asc';
        }
        else if (direction === 'asc') {
            newDir = 'desc';
        }
        else {
            newDir = null;
        }
        emit(SortChanged, { column, direction: newDir });
    }, [emit, column, isActive, direction]);
    const handleResizeStart = useCallback((e) => {
        e.stopPropagation();
        resizing.current = true;
        startX.current = e.clientX;
        startWidth.current = widths[column] || width;
        const handleMove = (me) => {
            if (!resizing.current)
                return;
            const diff = me.clientX - startX.current;
            emit(ColumnResized, { column, width: startWidth.current + diff });
        };
        const handleUp = () => {
            resizing.current = false;
            document.removeEventListener('mousemove', handleMove);
            document.removeEventListener('mouseup', handleUp);
        };
        document.addEventListener('mousemove', handleMove);
        document.addEventListener('mouseup', handleUp);
    }, [emit, column, width, widths]);
    return (_jsxs("th", { style: {
            width: widths[column] || width,
            minWidth: 50,
            padding: '10px 12px',
            textAlign: 'left',
            fontSize: 11,
            fontWeight: 700,
            color: '#64748b',
            textTransform: 'uppercase',
            letterSpacing: 0.5,
            cursor: 'pointer',
            userSelect: 'none',
            position: 'relative',
            borderBottom: '1px solid #1e293b',
            whiteSpace: 'nowrap',
        }, onClick: handleSort, children: [label, ' ', _jsx("span", { style: { color: isActive ? '#3b82f6' : '#334155', fontSize: 10 }, children: direction === 'asc' ? '\u25B2' : direction === 'desc' ? '\u25BC' : '\u25B2' }), _jsx("div", { onMouseDown: handleResizeStart, onClick: (e) => e.stopPropagation(), style: {
                    position: 'absolute',
                    right: 0,
                    top: 0,
                    bottom: 0,
                    width: 6,
                    cursor: 'col-resize',
                    background: 'transparent',
                }, onMouseEnter: (e) => {
                    e.currentTarget.style.background = 'rgba(59, 130, 246, 0.3)';
                }, onMouseLeave: (e) => {
                    e.currentTarget.style.background = 'transparent';
                } })] }));
}
// ---------------------------------------------------------------------------
// Expanded row detail
// ---------------------------------------------------------------------------
function ExpandedDetail({ row }) {
    return (_jsx("tr", { children: _jsx("td", { colSpan: 9, style: {
                padding: '16px 24px',
                background: '#111827',
                borderBottom: '1px solid #1e293b',
            }, children: _jsxs("div", { style: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, fontSize: 13 }, children: [_jsxs("div", { children: [_jsx("div", { style: { color: '#64748b', marginBottom: 4 }, children: "Full Details" }), _jsxs("div", { style: { color: '#e2e8f0' }, children: [_jsx("strong", { children: "Name:" }), " ", row.name, _jsx("br", {}), _jsx("strong", { children: "Email:" }), " ", row.email, _jsx("br", {}), _jsx("strong", { children: "Role:" }), " ", row.role, _jsx("br", {}), _jsx("strong", { children: "Status:" }), " ", row.status] })] }), _jsxs("div", { children: [_jsx("div", { style: { color: '#64748b', marginBottom: 4 }, children: "Activity" }), _jsxs("div", { style: { color: '#e2e8f0' }, children: [_jsx("strong", { children: "Created:" }), " ", row.created, _jsx("br", {}), _jsx("strong", { children: "Revenue:" }), " $", row.revenue.toLocaleString(), _jsx("br", {}), _jsx("strong", { children: "ID:" }), " ", row.id] })] })] }) }) }));
}
// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------
export default function App() {
    const emit = useEmit();
    const sort = useSignal(sortState);
    const filterState = useSignal(filters);
    const page = useSignal(currentPage);
    const selected = useSignal(selectedRows);
    const expanded = useSignal(expandedRows);
    const search = useSignal(searchQuery);
    const widths = useSignal(columnWidths);
    const loading = useSignal(isLoading);
    const { rows, totalRows, totalPages } = getProcessedData();
    const allVisibleSelected = rows.length > 0 && rows.every((r) => selected.has(r.id));
    return (_jsxs("div", { style: {
            minHeight: '100vh',
            background: '#0a0e17',
            fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
            color: '#e2e8f0',
            padding: 24,
        }, children: [_jsxs("div", { style: {
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    marginBottom: 20,
                }, children: [_jsxs("div", { children: [_jsx("h1", { style: { fontSize: 24, fontWeight: 700, margin: 0 }, children: "Data Table" }), _jsxs("p", { style: { color: '#64748b', fontSize: 13, marginTop: 4 }, children: [totalRows.toLocaleString(), " records | Page ", page, " of ", totalPages] })] }), _jsxs("div", { style: { display: 'flex', gap: 10, alignItems: 'center' }, children: [_jsx("input", { type: "text", placeholder: "Search...", value: search, onChange: (e) => emit(SearchChanged, e.target.value), style: {
                                    padding: '8px 12px',
                                    borderRadius: 8,
                                    border: '1px solid #334155',
                                    background: '#0f172a',
                                    color: '#e2e8f0',
                                    fontSize: 13,
                                    width: 220,
                                    outline: 'none',
                                } }), selected.size > 0 && (_jsxs("div", { style: { display: 'flex', gap: 6, alignItems: 'center' }, children: [_jsxs("span", { style: { fontSize: 12, color: '#3b82f6' }, children: [selected.size, " selected"] }), _jsxs("select", { onChange: (e) => {
                                            if (e.target.value) {
                                                emit(BulkAction, {
                                                    action: e.target.value,
                                                    ids: Array.from(selected),
                                                });
                                                e.target.value = '';
                                            }
                                        }, style: {
                                            padding: '6px 10px',
                                            borderRadius: 6,
                                            border: '1px solid #334155',
                                            background: '#0f172a',
                                            color: '#94a3b8',
                                            fontSize: 12,
                                        }, children: [_jsx("option", { value: "", children: "Bulk Actions..." }), _jsx("option", { value: "delete", children: "Delete" }), _jsx("option", { value: "activate", children: "Activate" }), _jsx("option", { value: "deactivate", children: "Deactivate" }), _jsx("option", { value: "export", children: "Export" })] }), _jsx("button", { onClick: () => emit(DeselectAll, undefined), style: {
                                            padding: '4px 8px',
                                            borderRadius: 4,
                                            border: '1px solid #334155',
                                            background: 'transparent',
                                            color: '#64748b',
                                            fontSize: 11,
                                            cursor: 'pointer',
                                        }, children: "Clear" })] }))] })] }), loading && (_jsx("div", { style: {
                    height: 2,
                    background: '#3b82f6',
                    borderRadius: 1,
                    marginBottom: 2,
                    animation: 'loading-bar 0.8s ease infinite',
                } })), _jsxs("div", { style: {
                    background: '#111827',
                    borderRadius: 12,
                    border: '1px solid #1e293b',
                    overflow: 'auto',
                }, children: [_jsxs("table", { style: {
                            width: '100%',
                            borderCollapse: 'collapse',
                            fontSize: 13,
                        }, children: [_jsxs("thead", { style: {
                                    position: 'sticky',
                                    top: 0,
                                    background: '#111827',
                                    zIndex: 10,
                                }, children: [_jsxs("tr", { children: [_jsx("th", { style: {
                                                    width: 40,
                                                    padding: '10px 12px',
                                                    borderBottom: '1px solid #1e293b',
                                                }, children: _jsx("input", { type: "checkbox", checked: allVisibleSelected, onChange: () => emit(SelectAll, undefined), style: { accentColor: '#3b82f6', cursor: 'pointer' } }) }), _jsx(SortHeader, { label: "ID", column: "id", width: 60 }), _jsx(SortHeader, { label: "Name", column: "name", width: 160 }), _jsx(SortHeader, { label: "Email", column: "email", width: 200 }), _jsx(SortHeader, { label: "Role", column: "role", width: 100 }), _jsx(SortHeader, { label: "Status", column: "status", width: 90 }), _jsx(SortHeader, { label: "Created", column: "created", width: 110 }), _jsx(SortHeader, { label: "Revenue", column: "revenue", width: 110 }), _jsx("th", { style: {
                                                    width: 80,
                                                    padding: '10px 12px',
                                                    textAlign: 'left',
                                                    fontSize: 11,
                                                    fontWeight: 700,
                                                    color: '#64748b',
                                                    textTransform: 'uppercase',
                                                    letterSpacing: 0.5,
                                                    borderBottom: '1px solid #1e293b',
                                                }, children: "Actions" })] }), _jsxs("tr", { children: [_jsx("td", { style: { padding: '6px 12px', borderBottom: '1px solid #1e293b' } }), _jsx("td", { style: { padding: '6px 12px', borderBottom: '1px solid #1e293b' } }), ['name', 'email', 'role', 'status', 'created'].map((col) => (_jsx("td", { style: { padding: '6px 8px', borderBottom: '1px solid #1e293b' }, children: _jsx("input", { type: "text", placeholder: `Filter...`, value: filterState[col] || '', onChange: (e) => emit(FilterChanged, { column: col, value: e.target.value }), style: {
                                                        width: '100%',
                                                        padding: '4px 6px',
                                                        borderRadius: 4,
                                                        border: '1px solid #1e293b',
                                                        background: '#0a0e17',
                                                        color: '#94a3b8',
                                                        fontSize: 11,
                                                        outline: 'none',
                                                    } }) }, col))), _jsx("td", { style: { padding: '6px 12px', borderBottom: '1px solid #1e293b' } }), _jsx("td", { style: { padding: '6px 12px', borderBottom: '1px solid #1e293b' } })] })] }), _jsx("tbody", { children: rows.map((row, i) => {
                                    const isSelected = selected.has(row.id);
                                    const isExpanded = expanded.has(row.id);
                                    const isEven = i % 2 === 0;
                                    return (_jsx(RowGroup, { row: row, isSelected: isSelected, isExpanded: isExpanded, isEven: isEven, search: search }, row.id));
                                }) })] }), rows.length === 0 && (_jsx("div", { style: {
                            padding: 40,
                            textAlign: 'center',
                            color: '#475569',
                            fontSize: 14,
                        }, children: "No results found" }))] }), _jsxs("div", { style: {
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    marginTop: 16,
                    fontSize: 13,
                    color: '#64748b',
                }, children: [_jsxs("span", { children: ["Showing ", (page - 1) * pageSize + 1, "-", Math.min(page * pageSize, totalRows), " of ", totalRows] }), _jsxs("div", { style: { display: 'flex', gap: 4 }, children: [_jsx(PageButton, { label: "\\u00AB", disabled: page <= 1, onClick: () => emit(PageChanged, 1) }), _jsx(PageButton, { label: "\\u2039", disabled: page <= 1, onClick: () => emit(PageChanged, page - 1) }), getPageNumbers(page, totalPages).map((p, i) => p === -1 ? (_jsx("span", { style: { padding: '6px 4px', color: '#475569' }, children: "..." }, `ellipsis-${i}`)) : (_jsx(PageButton, { label: String(p), active: p === page, disabled: false, onClick: () => emit(PageChanged, p) }, p))), _jsx(PageButton, { label: "\\u203A", disabled: page >= totalPages, onClick: () => emit(PageChanged, page + 1) }), _jsx(PageButton, { label: "\\u00BB", disabled: page >= totalPages, onClick: () => emit(PageChanged, totalPages) })] })] }), _jsx("style", { children: `
        @keyframes loading-bar {
          0% { transform: translateX(-100%); }
          50% { transform: translateX(0%); }
          100% { transform: translateX(100%); }
        }
      ` })] }));
}
// ---------------------------------------------------------------------------
// Row group (row + optional expansion)
// ---------------------------------------------------------------------------
function RowGroup({ row, isSelected, isExpanded, isEven, search, }) {
    const emit = useEmit();
    return (_jsxs(_Fragment, { children: [_jsxs("tr", { style: {
                    background: isSelected
                        ? 'rgba(59, 130, 246, 0.08)'
                        : isEven
                            ? '#0d1424'
                            : 'transparent',
                    transition: 'background 0.15s',
                }, onMouseEnter: (e) => {
                    if (!isSelected)
                        e.currentTarget.style.background = 'rgba(255,255,255,0.02)';
                }, onMouseLeave: (e) => {
                    if (!isSelected) {
                        e.currentTarget.style.background = isEven ? '#0d1424' : 'transparent';
                    }
                }, children: [_jsx("td", { style: { padding: '10px 12px', borderBottom: '1px solid #1e293b11' }, children: _jsx("input", { type: "checkbox", checked: isSelected, onChange: () => emit(RowSelected, row.id), style: { accentColor: '#3b82f6', cursor: 'pointer' } }) }), _jsx("td", { style: {
                            padding: '10px 12px',
                            borderBottom: '1px solid #1e293b11',
                            color: '#475569',
                            fontFamily: 'monospace',
                            fontSize: 11,
                        }, children: row.id.split('-')[1] }), _jsx("td", { style: {
                            padding: '10px 12px',
                            borderBottom: '1px solid #1e293b11',
                            fontWeight: 500,
                        }, children: _jsx(HighlightText, { text: row.name, query: search }) }), _jsx("td", { style: {
                            padding: '10px 12px',
                            borderBottom: '1px solid #1e293b11',
                            color: '#94a3b8',
                        }, children: _jsx(HighlightText, { text: row.email, query: search }) }), _jsx("td", { style: { padding: '10px 12px', borderBottom: '1px solid #1e293b11' }, children: _jsx(HighlightText, { text: row.role, query: search }) }), _jsx("td", { style: { padding: '10px 12px', borderBottom: '1px solid #1e293b11' }, children: _jsx(StatusBadge, { status: row.status }) }), _jsx("td", { style: {
                            padding: '10px 12px',
                            borderBottom: '1px solid #1e293b11',
                            fontFamily: 'monospace',
                            fontSize: 12,
                            color: '#94a3b8',
                        }, children: row.created }), _jsxs("td", { style: {
                            padding: '10px 12px',
                            borderBottom: '1px solid #1e293b11',
                            fontFamily: 'monospace',
                            fontSize: 12,
                            color: row.revenue > 500 ? '#4ade80' : '#94a3b8',
                            fontWeight: row.revenue > 500 ? 600 : 400,
                        }, children: ["$", row.revenue.toLocaleString()] }), _jsx("td", { style: { padding: '10px 12px', borderBottom: '1px solid #1e293b11' }, children: _jsx("button", { onClick: () => emit(RowExpanded, row.id), style: {
                                padding: '4px 8px',
                                borderRadius: 4,
                                border: '1px solid #334155',
                                background: isExpanded ? 'rgba(59, 130, 246, 0.15)' : 'transparent',
                                color: isExpanded ? '#60a5fa' : '#64748b',
                                fontSize: 11,
                                cursor: 'pointer',
                            }, children: isExpanded ? 'Close' : 'View' }) })] }), isExpanded && _jsx(ExpandedDetail, { row: row })] }));
}
// ---------------------------------------------------------------------------
// Page button
// ---------------------------------------------------------------------------
function PageButton({ label, active, disabled, onClick, }) {
    return (_jsx("button", { onClick: onClick, disabled: disabled, style: {
            padding: '6px 10px',
            borderRadius: 6,
            border: active ? '1px solid #3b82f6' : '1px solid #1e293b',
            background: active ? 'rgba(59, 130, 246, 0.2)' : 'transparent',
            color: disabled ? '#334155' : active ? '#3b82f6' : '#94a3b8',
            fontSize: 12,
            fontWeight: active ? 700 : 400,
            cursor: disabled ? 'default' : 'pointer',
            minWidth: 32,
        }, children: label }));
}
// ---------------------------------------------------------------------------
// Page number calculation
// ---------------------------------------------------------------------------
function getPageNumbers(current, total) {
    if (total <= 7) {
        return Array.from({ length: total }, (_, i) => i + 1);
    }
    const pages = [1];
    if (current > 3)
        pages.push(-1); // ellipsis
    const start = Math.max(2, current - 1);
    const end = Math.min(total - 1, current + 1);
    for (let i = start; i <= end; i++)
        pages.push(i);
    if (current < total - 2)
        pages.push(-1); // ellipsis
    pages.push(total);
    return pages;
}

// examples/solid/data-table/src/App.tsx
import { For, Show, onMount, onCleanup, createSignal as solidSignal } from 'solid-js'
import { useSignal, useEmit, useTween } from '@pulse/solid'
import type { Signal, TweenValue, EventType } from '@pulse/core'
import { engine } from './engine'

/* ------------------------------------------------------------------ */
/*  Types                                                             */
/* ------------------------------------------------------------------ */

interface Row {
  id: number
  name: string
  email: string
  department: string
  role: string
  salary: number
  startDate: string
  status: 'active' | 'inactive' | 'onleave'
}

type SortField = 'name' | 'department' | 'salary' | 'startDate' | 'status'
type SortDir = 'asc' | 'desc'

/* ------------------------------------------------------------------ */
/*  Data generation                                                   */
/* ------------------------------------------------------------------ */

const DEPARTMENTS = ['Engineering', 'Design', 'Marketing', 'Sales', 'HR', 'Finance', 'Legal', 'Operations']
const ROLES = ['Junior', 'Mid', 'Senior', 'Lead', 'Manager', 'Director', 'VP']
const STATUSES: Row['status'][] = ['active', 'inactive', 'onleave']
const FIRST = ['Alice', 'Bob', 'Carol', 'Dave', 'Eve', 'Frank', 'Grace', 'Hank', 'Ivy', 'Jack', 'Karen', 'Leo', 'Mia', 'Nate', 'Olivia', 'Pat', 'Quinn', 'Rose', 'Sam', 'Tina']
const LAST = ['Smith', 'Jones', 'Wilson', 'Brown', 'Davis', 'Miller', 'Moore', 'Taylor', 'Anderson', 'Thomas', 'Jackson', 'White', 'Harris', 'Martin', 'Garcia', 'Clark', 'Lewis', 'Lee', 'Walker', 'Hall']

function generateRows(count: number): Row[] {
  return Array.from({ length: count }, (_, i) => {
    const first = FIRST[i % FIRST.length]
    const last = LAST[Math.floor(i / FIRST.length) % LAST.length]
    const dept = DEPARTMENTS[i % DEPARTMENTS.length]
    const year = 2015 + (i % 9)
    const month = (i % 12) + 1
    return {
      id: i + 1,
      name: `${first} ${last}`,
      email: `${first.toLowerCase()}.${last.toLowerCase()}${i}@company.com`,
      department: dept,
      role: ROLES[i % ROLES.length],
      salary: 50000 + Math.floor(Math.random() * 120000),
      startDate: `${year}-${String(month).padStart(2, '0')}-${String((i % 28) + 1).padStart(2, '0')}`,
      status: STATUSES[i % 3],
    }
  })
}

const ALL_ROWS = generateRows(1000)

/* ------------------------------------------------------------------ */
/*  Events                                                            */
/* ------------------------------------------------------------------ */

const SetPage = engine.event<number>('SetPage')
const SetSort = engine.event<SortField>('SetSort')
const SetFilter = engine.event<string>('SetFilter')
const SetDeptFilter = engine.event<string>('SetDeptFilter')
const ToggleRowExpand = engine.event<number>('ToggleRowExpand')
const ToggleSelect = engine.event<number>('ToggleSelect')
const ToggleSelectAll = engine.event('ToggleSelectAll')
const BulkAction = engine.event<string>('BulkAction')
const ColumnResized = engine.event<{ col: string; width: number }>('ColumnResized')

// Async fetch simulation
const FetchPage = engine.event<number>('FetchPage')
const FetchPending = engine.event<number>('FetchPending')
const FetchDone = engine.event<{ page: number; rows: Row[]; total: number }>('FetchDone')
const FetchError = engine.event<{ error: string }>('FetchError')

// Row expand tween
const ExpandRowStart = engine.event('ExpandRowStart')
const expandRowTween: TweenValue = engine.tween({
  start: ExpandRowStart,
  from: 0,
  to: 1,
  duration: 250,
  easing: 'easeOut',
})

/* ------------------------------------------------------------------ */
/*  State                                                             */
/* ------------------------------------------------------------------ */

const PAGE_SIZE = 20

const currentPage = engine.signal<number>(SetPage, 0, (_prev, p) => p)
const sortField = engine.signal<SortField>(SetSort, 'name', (_prev, f) => f)
const sortDir = engine.signal<SortDir>(SetSort, 'asc' as SortDir, (prev, f) => {
  if (sortField.value === f) return prev === 'asc' ? 'desc' : 'asc'
  return 'asc'
})
const filterText = engine.signal<string>(SetFilter, '', (_prev, q) => q)
const deptFilter = engine.signal<string>(SetDeptFilter, '', (_prev, d) => d)
const expandedRow = engine.signal<number>(ToggleRowExpand, -1, (prev, id) => prev === id ? -1 : id)
const selectedRows = engine.signal<Set<number>>(
  ToggleSelect, new Set<number>(),
  (prev, id) => { const s = new Set(prev); if (s.has(id)) s.delete(id); else s.add(id); return s },
)
engine.signalUpdate(selectedRows, ToggleSelectAll, (prev) => {
  const pageRows = getPageRows()
  const allSelected = pageRows.every(r => prev.has(r.id))
  if (allSelected) return new Set<number>()
  return new Set(pageRows.map(r => r.id))
})
engine.signalUpdate(selectedRows, BulkAction, () => new Set<number>())

const isLoading = engine.signal<boolean>(FetchPending, false, () => true)
engine.signalUpdate(isLoading, FetchDone, () => false)
engine.signalUpdate(isLoading, FetchError, () => false)

const columnWidths = engine.signal<Record<string, number>>(
  ColumnResized, { name: 180, email: 220, department: 120, role: 100, salary: 100, startDate: 110, status: 90 },
  (prev, { col, width }) => ({ ...prev, [col]: Math.max(60, width) }),
)

engine.on(ToggleRowExpand, () => engine.emit(ExpandRowStart, undefined))

/* ------------------------------------------------------------------ */
/*  Async fetch                                                       */
/* ------------------------------------------------------------------ */

engine.async<number, { page: number; rows: Row[]; total: number }>(FetchPage, {
  pending: FetchPending,
  done: FetchDone,
  error: FetchError,
  strategy: 'latest',
  do: async (page) => {
    await new Promise(r => setTimeout(r, 150 + Math.random() * 200))
    const filtered = getFilteredSorted()
    const start = page * PAGE_SIZE
    return { page, rows: filtered.slice(start, start + PAGE_SIZE), total: filtered.length }
  },
})

/* ------------------------------------------------------------------ */
/*  Derived data helpers                                              */
/* ------------------------------------------------------------------ */

function getFilteredSorted(): Row[] {
  let rows = [...ALL_ROWS]
  const q = filterText.value.toLowerCase()
  const dept = deptFilter.value

  if (q) rows = rows.filter(r => r.name.toLowerCase().includes(q) || r.email.toLowerCase().includes(q))
  if (dept) rows = rows.filter(r => r.department === dept)

  const field = sortField.value
  const dir = sortDir.value === 'asc' ? 1 : -1
  rows.sort((a, b) => {
    const av = a[field]
    const bv = b[field]
    if (typeof av === 'string' && typeof bv === 'string') return av.localeCompare(bv) * dir
    return ((av as number) - (bv as number)) * dir
  })

  return rows
}

function getPageRows(): Row[] {
  const filtered = getFilteredSorted()
  const start = currentPage.value * PAGE_SIZE
  return filtered.slice(start, start + PAGE_SIZE)
}

/* ------------------------------------------------------------------ */
/*  Components                                                        */
/* ------------------------------------------------------------------ */

const STATUS_COLORS: Record<string, string> = { active: '#00b894', inactive: '#d63031', onleave: '#fdcb6e' }

function SortHeader(props: { field: SortField; label: string }) {
  const emit = useEmit()
  const sf = useSignal(sortField)
  const sd = useSignal(sortDir)
  const widths = useSignal(columnWidths)

  let resizing = false
  let startX = 0
  let startW = 0

  const onResizeDown = (e: PointerEvent) => {
    e.stopPropagation()
    resizing = true
    startX = e.clientX
    startW = widths()[props.field] ?? 100
    const move = (ev: PointerEvent) => {
      const dx = ev.clientX - startX
      emit(ColumnResized, { col: props.field, width: startW + dx })
    }
    const up = () => { resizing = false; window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up) }
    window.addEventListener('pointermove', move)
    window.addEventListener('pointerup', up)
  }

  return (
    <th
      onClick={() => emit(SetSort, props.field)}
      style={{
        width: `${widths()[props.field]}px`, padding: '10px 12px', 'text-align': 'left',
        'font-size': '12px', 'font-weight': '600', color: '#666', cursor: 'pointer',
        'text-transform': 'uppercase', 'letter-spacing': '0.5px',
        background: '#fafafa', 'border-bottom': '2px solid #e0e0e0',
        'user-select': 'none', position: 'relative',
      }}
    >
      {props.label}
      {sf() === props.field && <span style={{ 'margin-left': '4px' }}>{sd() === 'asc' ? '\u25B2' : '\u25BC'}</span>}
      <div
        onPointerDown={onResizeDown}
        style={{
          position: 'absolute', right: '0', top: '0', bottom: '0', width: '6px',
          cursor: 'col-resize', background: resizing ? '#4361ee' : 'transparent',
        }}
      />
    </th>
  )
}

function DataRow(props: { row: Row }) {
  const emit = useEmit()
  const expanded = useSignal(expandedRow)
  const selected = useSignal(selectedRows)
  const expandVal = useTween(expandRowTween)

  const isExpanded = () => expanded() === props.row.id
  const isSelected = () => selected().has(props.row.id)

  return (
    <>
      <tr
        onClick={() => emit(ToggleRowExpand, props.row.id)}
        style={{
          cursor: 'pointer',
          background: isSelected() ? '#e8f0fe' : isExpanded() ? '#f8f9fa' : '#fff',
          'border-bottom': '1px solid #f0f0f0',
          transition: 'background 0.15s',
        }}
      >
        <td style={{ padding: '10px 12px', 'text-align': 'center' }}>
          <input
            type="checkbox"
            checked={isSelected()}
            onClick={(e) => { e.stopPropagation(); emit(ToggleSelect, props.row.id) }}
          />
        </td>
        <td style={{ padding: '10px 12px', 'font-weight': '500', color: '#333', 'font-size': '13px' }}>{props.row.name}</td>
        <td style={{ padding: '10px 12px', color: '#666', 'font-size': '13px' }}>{props.row.email}</td>
        <td style={{ padding: '10px 12px', color: '#666', 'font-size': '13px' }}>{props.row.department}</td>
        <td style={{ padding: '10px 12px', color: '#666', 'font-size': '13px' }}>{props.row.role}</td>
        <td style={{ padding: '10px 12px', 'font-size': '13px', 'font-weight': '500' }}>${props.row.salary.toLocaleString()}</td>
        <td style={{ padding: '10px 12px', color: '#888', 'font-size': '12px' }}>{props.row.startDate}</td>
        <td style={{ padding: '10px 12px' }}>
          <span style={{
            padding: '2px 10px', 'border-radius': '10px', 'font-size': '11px', 'font-weight': '600',
            background: STATUS_COLORS[props.row.status] + '22', color: STATUS_COLORS[props.row.status],
          }}>{props.row.status}</span>
        </td>
      </tr>
      <Show when={isExpanded()}>
        <tr>
          <td colspan="8" style={{
            padding: '16px 24px', background: '#f8f9fa', 'border-bottom': '1px solid #e0e0e0',
            overflow: 'hidden',
            'max-height': `${expandVal() * 120}px`,
            opacity: String(expandVal()),
          }}>
            <div style={{ display: 'grid', 'grid-template-columns': 'repeat(3, 1fr)', gap: '12px', 'font-size': '13px' }}>
              <div><strong>Full Name:</strong> {props.row.name}</div>
              <div><strong>Email:</strong> {props.row.email}</div>
              <div><strong>Department:</strong> {props.row.department}</div>
              <div><strong>Role:</strong> {props.row.role}</div>
              <div><strong>Salary:</strong> ${props.row.salary.toLocaleString()}</div>
              <div><strong>Start Date:</strong> {props.row.startDate}</div>
              <div><strong>Status:</strong> {props.row.status}</div>
              <div><strong>Employee ID:</strong> #{props.row.id.toString().padStart(5, '0')}</div>
            </div>
          </td>
        </tr>
      </Show>
    </>
  )
}

export default function App() {
  const emit = useEmit()
  const page = useSignal(currentPage)
  const filter = useSignal(filterText)
  const dept = useSignal(deptFilter)
  const loading = useSignal(isLoading)
  const selected = useSignal(selectedRows)

  const pageRows = () => getPageRows()
  const totalFiltered = () => getFilteredSorted().length
  const totalPages = () => Math.ceil(totalFiltered() / PAGE_SIZE)

  return (
    <div style={{
      'min-height': '100vh', padding: '24px',
      'font-family': '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    }}>
      {/* Header */}
      <div style={{ display: 'flex', 'justify-content': 'space-between', 'align-items': 'center', 'margin-bottom': '16px' }}>
        <div>
          <h1 style={{ 'font-size': '24px', 'font-weight': '700', color: '#333', margin: '0' }}>Data Table</h1>
          <p style={{ 'font-size': '13px', color: '#888', margin: '4px 0 0' }}>1,000 rows &middot; Sort, filter, paginate, expand, bulk actions</p>
        </div>
        <Show when={selected().size > 0}>
          <div style={{ display: 'flex', gap: '8px', 'align-items': 'center' }}>
            <span style={{ 'font-size': '13px', color: '#4361ee', 'font-weight': '600' }}>{selected().size} selected</span>
            <button onClick={() => emit(BulkAction, 'delete')} style={{ padding: '6px 16px', 'border-radius': '6px', border: 'none', background: '#d63031', color: '#fff', cursor: 'pointer', 'font-size': '12px' }}>Delete</button>
            <button onClick={() => emit(BulkAction, 'export')} style={{ padding: '6px 16px', 'border-radius': '6px', border: 'none', background: '#4361ee', color: '#fff', cursor: 'pointer', 'font-size': '12px' }}>Export</button>
          </div>
        </Show>
      </div>

      {/* Filters */}
      <div style={{ display: 'flex', gap: '12px', 'margin-bottom': '16px' }}>
        <input
          placeholder="Search by name or email..."
          value={filter()}
          onInput={(e) => { emit(SetFilter, e.currentTarget.value); emit(SetPage, 0) }}
          style={{ flex: '1', padding: '10px 14px', 'font-size': '13px', border: '1px solid #ddd', 'border-radius': '8px', outline: 'none' }}
        />
        <select
          value={dept()}
          onChange={(e) => { emit(SetDeptFilter, e.currentTarget.value); emit(SetPage, 0) }}
          style={{ padding: '10px 14px', 'font-size': '13px', border: '1px solid #ddd', 'border-radius': '8px', outline: 'none', background: '#fff' }}
        >
          <option value="">All Departments</option>
          <For each={DEPARTMENTS}>{(d) => <option value={d}>{d}</option>}</For>
        </select>
      </div>

      {/* Table */}
      <div style={{ background: '#fff', 'border-radius': '8px', 'box-shadow': '0 1px 4px rgba(0,0,0,0.1)', overflow: 'auto', 'margin-bottom': '16px' }}>
        <table style={{ width: '100%', 'border-collapse': 'collapse' }}>
          <thead>
            <tr>
              <th style={{ width: '40px', padding: '10px', background: '#fafafa', 'border-bottom': '2px solid #e0e0e0' }}>
                <input type="checkbox" onChange={() => emit(ToggleSelectAll, undefined)} />
              </th>
              <SortHeader field="name" label="Name" />
              <th style={{ padding: '10px 12px', 'text-align': 'left', 'font-size': '12px', 'font-weight': '600', color: '#666', background: '#fafafa', 'border-bottom': '2px solid #e0e0e0' }}>Email</th>
              <SortHeader field="department" label="Department" />
              <th style={{ padding: '10px 12px', 'text-align': 'left', 'font-size': '12px', 'font-weight': '600', color: '#666', background: '#fafafa', 'border-bottom': '2px solid #e0e0e0' }}>Role</th>
              <SortHeader field="salary" label="Salary" />
              <SortHeader field="startDate" label="Start Date" />
              <SortHeader field="status" label="Status" />
            </tr>
          </thead>
          <tbody>
            <Show when={!loading()} fallback={
              <For each={Array.from({ length: 5 })}>{() => (
                <tr><td colspan="8" style={{ padding: '16px', 'text-align': 'center', color: '#888' }}>Loading...</td></tr>
              )}</For>
            }>
              <For each={pageRows()}>
                {(row) => <DataRow row={row} />}
              </For>
            </Show>
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      <div style={{ display: 'flex', 'justify-content': 'space-between', 'align-items': 'center' }}>
        <span style={{ 'font-size': '13px', color: '#888' }}>
          Showing {page() * PAGE_SIZE + 1}-{Math.min((page() + 1) * PAGE_SIZE, totalFiltered())} of {totalFiltered()}
        </span>
        <div style={{ display: 'flex', gap: '4px' }}>
          <button
            disabled={page() === 0}
            onClick={() => emit(SetPage, page() - 1)}
            style={{ padding: '6px 12px', 'border-radius': '6px', border: '1px solid #ddd', background: '#fff', cursor: page() > 0 ? 'pointer' : 'default', 'font-size': '13px' }}
          >Prev</button>
          <For each={Array.from({ length: Math.min(5, totalPages()) }, (_, i) => {
            const start = Math.max(0, Math.min(page() - 2, totalPages() - 5))
            return start + i
          })}>
            {(p) => (
              <button
                onClick={() => emit(SetPage, p)}
                style={{
                  padding: '6px 12px', 'border-radius': '6px', 'font-size': '13px',
                  border: page() === p ? 'none' : '1px solid #ddd',
                  background: page() === p ? '#4361ee' : '#fff',
                  color: page() === p ? '#fff' : '#333',
                  cursor: 'pointer',
                }}
              >{p + 1}</button>
            )}
          </For>
          <button
            disabled={page() >= totalPages() - 1}
            onClick={() => emit(SetPage, page() + 1)}
            style={{ padding: '6px 12px', 'border-radius': '6px', border: '1px solid #ddd', background: '#fff', cursor: page() < totalPages() - 1 ? 'pointer' : 'default', 'font-size': '13px' }}
          >Next</button>
        </div>
      </div>
    </div>
  )
}
