// examples/solid/drag-api-animation/src/App.tsx
import { onMount } from 'solid-js'
import { usePulse, useEmit } from '@pulse/solid'
import {
  CardsChanged,
  DragStateChanged,
  DragPositionChanged,
  CardStatusesChanged,
  DragStart,
  DragMove,
  DragEnd,
  CardMoved,
  UndoRequested,
  type KanbanCard,
  type ColumnId,
  type CardStatus,
} from './engine'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const COLUMNS: { id: ColumnId; title: string; color: string }[] = [
  { id: 'todo', title: 'Todo', color: '#4361ee' },
  { id: 'in-progress', title: 'In Progress', color: '#f59e0b' },
  { id: 'done', title: 'Done', color: '#10b981' },
]

const PRIORITY_COLORS: Record<string, string> = {
  low: '#10b981',
  medium: '#f59e0b',
  high: '#ef4444',
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = {
  container: {
    'min-height': '100vh',
    background: '#0f172a',
    padding: '32px 24px',
    'font-family':
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  header: {
    'text-align': 'center' as const,
    'margin-bottom': 32,
  },
  title: {
    'font-size': 36,
    'font-weight': 800,
    color: '#f1f5f9',
    margin: 0,
  },
  subtitle: {
    color: '#94a3b8',
    'font-size': 14,
    'margin-top': 6,
  },
  board: {
    display: 'grid',
    'grid-template-columns': 'repeat(3, 1fr)',
    gap: 20,
    'max-width': 1100,
    margin: '0 auto',
  },
  column: (color: string) =>
    ({
      background: '#1e293b',
      'border-radius': 16,
      padding: 16,
      'min-height': 400,
      'border-top': `3px solid ${color}`,
    }),
  columnHeader: {
    display: 'flex',
    'align-items': 'center',
    'justify-content': 'space-between',
    'margin-bottom': 16,
    padding: '0 4px',
  },
  columnTitle: {
    'font-size': 16,
    'font-weight': 700,
    color: '#e2e8f0',
  },
  columnCount: (color: string) =>
    ({
      'font-size': 13,
      'font-weight': 600,
      color: color,
      background: `${color}22`,
      padding: '2px 10px',
      'border-radius': 12,
    }),
  card: (status: CardStatus, isDragging: boolean) => {
    let borderColor = '#334155'
    let bg = '#0f172a'
    if (status === 'saving') {
      borderColor = '#f59e0b'
    } else if (status === 'saved') {
      borderColor = '#10b981'
      bg = '#10b98108'
    } else if (status === 'error') {
      borderColor = '#ef4444'
      bg = '#ef444408'
    }
    return {
      background: bg,
      border: `2px solid ${borderColor}`,
      'border-radius': 12,
      padding: 16,
      'margin-bottom': 10,
      cursor: isDragging ? 'grabbing' : 'grab',
      opacity: isDragging ? 0.4 : 1,
      transition: 'border-color 0.3s, background 0.3s, opacity 0.15s',
      'user-select': 'none' as const,
    }
  },
  cardTitle: {
    'font-size': 15,
    'font-weight': 600,
    color: '#e2e8f0',
    margin: 0,
    'margin-bottom': 4,
  },
  cardDesc: {
    'font-size': 13,
    color: '#94a3b8',
    margin: 0,
    'margin-bottom': 10,
  },
  cardFooter: {
    display: 'flex',
    'align-items': 'center',
    'justify-content': 'space-between',
  },
  priorityBadge: (priority: string) =>
    ({
      'font-size': 11,
      'font-weight': 600,
      'text-transform': 'uppercase' as const,
      color: PRIORITY_COLORS[priority] ?? '#94a3b8',
      background: `${PRIORITY_COLORS[priority] ?? '#94a3b8'}22`,
      padding: '2px 8px',
      'border-radius': 8,
    }),
  statusBadge: (status: CardStatus) => {
    const map: Record<CardStatus, { color: string; label: string }> = {
      idle: { color: '#64748b', label: '' },
      saving: { color: '#f59e0b', label: 'Saving...' },
      saved: { color: '#10b981', label: 'Saved' },
      error: { color: '#ef4444', label: 'Error - retrying' },
      settled: { color: '#64748b', label: '' },
    }
    const info = map[status]
    if (!info.label) return { display: 'none' }
    return {
      'font-size': 11,
      'font-weight': 600,
      color: info.color,
    }
  },
  undoBtn: {
    'font-size': 12,
    color: '#94a3b8',
    background: 'none',
    border: '1px solid #334155',
    'border-radius': 6,
    padding: '2px 8px',
    cursor: 'pointer',
    'margin-left': 8,
  },
  ghostCard: {
    position: 'fixed' as const,
    'pointer-events': 'none' as const,
    'z-index': 1000,
    width: 300,
    background: '#1e293b',
    border: '2px solid #4361ee',
    'border-radius': 12,
    padding: 16,
    'box-shadow': '0 20px 40px rgba(0,0,0,0.5)',
  },
  dropZone: {
    'min-height': 60,
    border: '2px dashed transparent',
    'border-radius': 8,
    transition: 'border-color 0.2s, background 0.2s',
    background: 'transparent',
  },
}

// ---------------------------------------------------------------------------
// CardComponent
// ---------------------------------------------------------------------------

function KanbanCardComponent({ card }: { card: KanbanCard }) {
  const emit = useEmit()
  const drag = usePulse(DragStateChanged, null as ReturnType<typeof DragStateChanged['__type']> | null)
  const statuses = usePulse(CardStatusesChanged, {} as Record<string, CardStatus>)
  let cardRef = null

  const status: CardStatus = statuses()[card.id] ?? 'idle'
  const isDragging = drag()?.cardId === card.id

  const statusLabels: Record<CardStatus, string> = {
    idle: '',
    saving: 'Saving...',
    saved: 'Saved',
    error: 'Error - retrying',
    settled: '',
  }

  const handleMouseDown = 
    (e: MouseEvent) => {
      e.preventDefault()
      const rect = cardRef?.getBoundingClientRect()
      if (!rect) return
      emit(DragStart, {
        cardId: card.id,
        startX: e.clientX,
        startY: e.clientY,
        offsetX: e.clientX - rect.left,
        offsetY: e.clientY - rect.top,
      })
    }
  return (
    <div
      ref={cardRef}
      style={{
        ...styles.card(status, isDragging),
        animation:
          status === 'error'
            ? 'shake 0.5s ease-in-out'
            : status === 'saved'
              ? 'flashGreen 0.6s ease-out'
              : undefined,
      }}
      onMouseDown={handleMouseDown}
    >
      <p style={styles.cardTitle}>{card.title}</p>
      <p style={styles.cardDesc}>{card.description}</p>
      <div style={styles.cardFooter}>
        <span style={styles.priorityBadge(card.priority)}>{card.priority}</span>
        <span>
          <span style={styles.statusBadge(status)}>{statusLabels[status]}</span>
          {(status === 'saved' || status === 'error') && (
            <button
              style={styles.undoBtn}
              onClick={(e) => {
                e.stopPropagation()
                emit(UndoRequested, card.id)
              }}
            >
              Undo
            </button>
          )}
        </span>
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Ghost card
// ---------------------------------------------------------------------------

function GhostCard() {
  const drag = usePulse(DragStateChanged, null as any)
  const allCards = usePulse(CardsChanged, [] as KanbanCard[])
  const springPos = usePulse(DragPositionChanged, { x: 0, y: 0 })

  if (!drag()) return null

  const card = allCards().find((c) => c.id === drag().cardId)
  if (!card) return null

  return (
    <div
      style={{
        ...styles.ghostCard,
        left: springPos.x - drag().offsetX,
        top: springPos.y - drag().offsetY,
      }}
    >
      <p style={styles.cardTitle}>{card.title}</p>
      <p style={styles.cardDesc}>{card.description}</p>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Column
// ---------------------------------------------------------------------------

function Column({
  id,
  title,
  color,
}: {
  id: ColumnId
  title: string
  color: string
}) {
  const allCards = usePulse(CardsChanged, [] as KanbanCard[])
  const drag = usePulse(DragStateChanged, null as any)
  const emit = useEmit()

  const columnCards = allCards().filter((c) => c.column === id)
  const isDragging = drag() !== null

  return (
    <div style={styles.column(color)}>
      <div style={styles.columnHeader}>
        <span style={styles.columnTitle}>{title}</span>
        <span style={styles.columnCount(color)}>{columnCards.length}</span>
      </div>
      {columnCards.map((card) => (
        <KanbanCardComponent card={card} />
      ))}
      {isDragging && (
        <div
          style={styles.dropZone}
          onMouseEnter={(e) => {
            e.currentTarget.style.borderColor = '#4361ee'
            e.currentTarget.style.background = '#4361ee11'
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.borderColor = 'transparent'
            e.currentTarget.style.background = 'transparent'
          }}
          onMouseUp={() => {
            if (drag()) {
              const card = allCards().find((c) => c.id === drag().cardId)
              if (card && card.column !== id) {
                emit(CardMoved, {
                  cardId: drag.cardId,
                  fromColumn: card.column,
                  toColumn: id,
                })
              }
              emit(DragEnd, undefined)
            }
          }}
        >
          <div
            style={{
              padding: 20,
              'text-align': 'center',
              color: '#475569',
              'font-size': 13,
            }}
          >
            Drop here
          </div>
        </div>
      )}
    </div>
  )
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

export default function App() {
  const emit = useEmit()
  const drag = usePulse(DragStateChanged, null as any)

  // Global mouse move/up handlers for drag()
  onMount(() => {
    const handleMouseMove = (e: MouseEvent) => {
      if (drag()) {
        emit(DragMove, { x: e.clientX, y: e.clientY })
      }
    }

    const handleMouseUp = () => {
      if (drag()) {
        emit(DragEnd, undefined)
      }
    }

    window.addEventListener('mousemove', handleMouseMove)
    window.addEventListener('mouseup', handleMouseUp)
    return () => {
      window.removeEventListener('mousemove', handleMouseMove)
      window.removeEventListener('mouseup', handleMouseUp)
    }
  })

  return (
    <div style={styles.container}>
      {/* Animations */}
      <style>{`
        @keyframes shake {
          0%, 100% { transform: translateX(0); }
          10%, 30%, 50%, 70%, 90% { transform: translateX(-4px); }
          20%, 40%, 60%, 80% { transform: translateX(4px); }
        }
        @keyframes flashGreen {
          0% { background: #10b98122; }
          100% { background: #0f172a; }
        }
      `}</style>

      <div style={styles.header}>
        <h1 style={styles.title}>Pulse Kanban</h1>
        <p style={styles.subtitle}>
          Drag cards between columns. Spring physics follow your mouse.
          Saves auto-retry on failure.
        </p>
      </div>

      <div style={styles.board}>
        {COLUMNS.map((col) => (
          <Column id={col.id} title={col.title} color={col.color} />
        ))}
      </div>

      <GhostCard />
    </div>
  )
}

// examples/angular/drag-api-animation/src/app.component.ts
import { Component, computed, type WritableSignal } from '@angular/core'
import { PulseService } from '@pulse/angular'
import {
  CardDragEnd,
  CardMoved,
  RetryLastSave,
  cardsSig,
  savingSig,
  saveErrorSig,
  lastMoveSig,
  snapSpring,
  type KanbanCard,
  type ColumnId,
  type MovePayload,
} from './engine'

interface Column {
  id: ColumnId
  title: string
}

@Component({
  selector: 'app-root',
  standalone: true,
  providers: [PulseService],
  template: `
    <div class="container">
      <h1>Kanban Board</h1>
      <p class="subtitle">Drag cards between columns. Spring animation + async save with retry.</p>

      @if (saving()) {
        <div class="status saving">Saving...</div>
      }
      @if (saveError()) {
        <div class="status error">
          {{ saveError() }}
          <button (click)="retry()">Retry</button>
        </div>
      }

      <div class="board">
        @for (col of columns; track col.id) {
          <div
            class="column"
            (dragover)="onDragOver($event)"
            (drop)="onDrop($event, col.id)"
          >
            <h2>{{ col.title }} ({{ getColumnCards(col.id).length }})</h2>
            <div class="card-list">
              @for (card of getColumnCards(col.id); track card.id) {
                <div
                  class="card"
                  draggable="true"
                  (dragstart)="onDragStart($event, card)"
                  (dragend)="onDragEndEvent($event)"
                  [style.transform]="'scale(' + springScale() + ')'"
                  [attr.data-card-id]="card.id"
                >
                  <span class="card-title">{{ card.title }}</span>
                  <span class="card-id">#{{ card.id }}</span>
                </div>
              } @empty {
                <div class="empty-col">Drop cards here</div>
              }
            </div>
          </div>
        }
      </div>
    </div>
  `,
  styles: [`
    .container {
      max-width: 900px;
      margin: 0 auto;
    }
    h1 { text-align: center; margin-bottom: 0.25rem; }
    .subtitle {
      text-align: center;
      color: #888;
      margin-bottom: 1rem;
      font-size: 0.9rem;
    }
    .status {
      text-align: center;
      padding: 0.5rem 1rem;
      border-radius: 6px;
      margin-bottom: 1rem;
    }
    .status.saving {
      background: #fef9e7;
      color: #f39c12;
    }
    .status.error {
      background: #fce4e4;
      color: #c0392b;
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 0.75rem;
    }
    .status.error button {
      padding: 0.25rem 0.75rem;
      border: 1px solid #c0392b;
      border-radius: 4px;
      background: white;
      color: #c0392b;
      cursor: pointer;
      font-size: 0.85rem;
    }
    .board {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 1rem;
    }
    .column {
      background: #e8eaed;
      border-radius: 8px;
      padding: 1rem;
      min-height: 300px;
    }
    .column h2 {
      font-size: 0.95rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: #555;
      margin-bottom: 0.75rem;
    }
    .card-list {
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
    }
    .card {
      background: white;
      border-radius: 6px;
      padding: 0.75rem;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
      cursor: grab;
      display: flex;
      justify-content: space-between;
      align-items: center;
      transition: box-shadow 0.2s;
      will-change: transform;
    }
    .card:hover {
      box-shadow: 0 3px 8px rgba(0,0,0,0.15);
    }
    .card:active {
      cursor: grabbing;
    }
    .card-title {
      font-size: 0.9rem;
      font-weight: 500;
    }
    .card-id {
      font-size: 0.75rem;
      color: #aaa;
    }
    .empty-col {
      text-align: center;
      color: #aaa;
      padding: 2rem 0;
      font-size: 0.85rem;
      border: 2px dashed #ccc;
      border-radius: 6px;
    }
  `],
})
export class AppComponent {
  columns: Column[] = [
    { id: 'todo', title: 'To Do' },
    { id: 'in-progress', title: 'In Progress' },
    { id: 'done', title: 'Done' },
  ]

  cards: WritableSignal<KanbanCard[]>
  saving: WritableSignal<boolean>
  saveError: WritableSignal<string | null>
  lastMove: WritableSignal<MovePayload | null>
  springVal: WritableSignal<number>

  springScale = computed(() => {
    // Use the spring value to create a subtle scale bounce on drop
    const v = this.springVal()
    return 1 + v * 0.05
  })

  private draggedCardId: number | null = null

  constructor(private pulse: PulseService) {
    this.cards = pulse.signal(cardsSig)
    this.saving = pulse.signal(savingSig)
    this.saveError = pulse.signal(saveErrorSig)
    this.lastMove = pulse.signal(lastMoveSig)
    this.springVal = pulse.spring(snapSpring)
  }

  getColumnCards(columnId: ColumnId): KanbanCard[] {
    return this.cards().filter((c) => c.column === columnId)
  }

  onDragStart(event: DragEvent, card: KanbanCard): void {
    this.draggedCardId = card.id
    if (event.dataTransfer) {
      event.dataTransfer.effectAllowed = 'move'
      event.dataTransfer.setData('text/plain', String(card.id))
    }
  }

  onDragOver(event: DragEvent): void {
    event.preventDefault()
    if (event.dataTransfer) {
      event.dataTransfer.dropEffect = 'move'
    }
  }

  onDrop(event: DragEvent, toColumn: ColumnId): void {
    event.preventDefault()
    const cardId = this.draggedCardId
    if (cardId == null) return

    // Only move if the card is not already in this column
    const card = this.cards().find((c) => c.id === cardId)
    if (card && card.column !== toColumn) {
      this.pulse.emit(CardDragEnd, { cardId, toColumn })
    }
    this.draggedCardId = null
  }

  onDragEndEvent(_event: DragEvent): void {
    this.draggedCardId = null
  }

  retry(): void {
    const last = this.lastMove()
    if (last) {
      this.pulse.emit(CardMoved, last)
    }
  }
}
