// examples/solid/notification-system/src/App.tsx
import { usePulse, useEmit } from '@pulse/solid'
import {
  NotificationsChanged,
  NotifyInfo,
  NotifySuccess,
  NotifyWarning,
  NotifyError,
  DismissNotification,
  DismissAll,
} from './engine'
import type { Notification, NotificationType } from './engine'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const MAX_VISIBLE = 5

const TYPE_COLORS: Record<NotificationType, { bg: string; border: string; icon: string }> = {
  info: { bg: 'rgba(59, 130, 246, 0.15)', border: 'rgba(59, 130, 246, 0.4)', icon: '#3b82f6' },
  success: { bg: 'rgba(34, 197, 94, 0.15)', border: 'rgba(34, 197, 94, 0.4)', icon: '#22c55e' },
  warning: { bg: 'rgba(245, 158, 11, 0.15)', border: 'rgba(245, 158, 11, 0.4)', icon: '#f59e0b' },
  error: { bg: 'rgba(239, 68, 68, 0.15)', border: 'rgba(239, 68, 68, 0.4)', icon: '#ef4444' },
}

const TYPE_ICONS: Record<NotificationType, string> = {
  info: '\u2139',
  success: '\u2713',
  warning: '\u26A0',
  error: '\u2717',
}

// ---------------------------------------------------------------------------
// NotificationItem
// ---------------------------------------------------------------------------

function NotificationItem({
  notif,
  index,
  onDismiss,
}: {
  notif: Notification
  index: number
  onDismiss: (id: string) => void
}) {
  const colors = TYPE_COLORS[notif.type]
  const icon = TYPE_ICONS[notif.type]

  const isEntering = notif.entering
  const isExiting = notif.exiting

  return (
    <div
      style={{
        position: 'relative',
        padding: '14px 44px 14px 16px',
        'border-radius': 12,
        background: colors.bg,
        'backdrop-filter': 'blur(20px)',
        WebkitBackdropFilter: 'blur(20px)',
        border: `1px solid ${colors.border}`,
        'box-shadow': '0 8px 32px rgba(0, 0, 0, 0.12)',
        transform: isEntering
          ? 'translateX(120%)'
          : isExiting
            ? 'translateX(120%) scale(0.95)'
            : 'translateX(0)',
        opacity: isEntering ? 0 : isExiting ? 0 : 1,
        transition: 'transform 0.4s cubic-bezier(0.22, 1, 0.36, 1), opacity 0.35s ease',
        'margin-bottom': 10,
        'min-width': 320,
        'max-width': 400,
      }}
    >
      <div style={{ display: 'flex', 'align-items': 'flex-start', gap: 10 }}>
        <span
          style={{
            'font-size': 18,
            color: colors.icon,
            'line-height': 1,
            'margin-top': 2,
            'font-weight': 700,
          }}
        >
          {icon}
        </span>
        <div style={{ flex: 1, 'min-width': 0 }}>
          <div
            style={{
              'font-weight': 600,
              'font-size': 14,
              color: '#e2e8f0',
              'margin-bottom': 2,
            }}
          >
            {notif.title}
          </div>
          <div style={{ 'font-size': 13, color: '#94a3b8', 'line-height': 1.4 }}>
            {notif.message}
          </div>
        </div>
      </div>
      <button
        onClick={() => onDismiss(notif.id)}
        style={{
          position: 'absolute',
          top: 10,
          right: 10,
          background: 'none',
          border: 'none',
          color: '#64748b',
          cursor: 'pointer',
          'font-size': 16,
          'line-height': 1,
          padding: '2px 6px',
          'border-radius': 4,
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.color = '#e2e8f0'
          e.currentTarget.style.background = 'rgba(255,255,255,0.1)'
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.color = '#64748b'
          e.currentTarget.style.background = 'none'
        }}
      >
        \u2715
      </button>
    </div>
  )
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

export default function App() {
  const emit = useEmit()
  const allNotifications = usePulse(NotificationsChanged, [] as Notification[])
  const count = usePulse(NotificationCountChanged, 0)

  const visibleNotifications = allNotifications().slice(0, MAX_VISIBLE)
  const queuedCount = Math.max(0, allNotifications().length - MAX_VISIBLE)

  const handleDismiss = (id: string) => emit(DismissNotification, id)
  const handleFlood = () => {
    const types: Array<{ event: typeof NotifyInfo; type: string }> = [
      { event: NotifyInfo, type: 'Info' },
      { event: NotifySuccess, type: 'Success' },
      { event: NotifyWarning, type: 'Warning' },
      { event: NotifyError, type: 'Error' },
    ]
    for (let i = 0; i < 20; i++) {
      const t = types[i % types.length]
      setTimeout(
        () =>
          emit(t.event, {
            title: `${t.type} #${i + 1}`,
            message: `Flood notification message number ${i + 1}`,
          }),
        i * 80,
      )
    }
  }

  return (
    <div
      style={{
        'min-height': '100vh',
        background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0f172a 100%)',
        'font-family':
          '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        padding: 40,
        position: 'relative',
      }}
    >
      {/* Header */}
      <div style={{ 'max-width': 600, margin: '0 auto', 'text-align': 'center' }}>
        <h1
          style={{
            'font-size': 32,
            'font-weight': 800,
            color: '#f1f5f9',
            'margin-bottom': 8,
          }}
        >
          Notification System
        </h1>
        <p style={{ color: '#64748b', 'font-size': 14, 'margin-bottom': 40 }}>
          Toast notifications with priority ordering, auto-dismiss, and animated
          transitions. Max {MAX_VISIBLE} visible at a time.
        </p>

        {/* Control buttons */}
        <div
          style={{
            display: 'flex',
            'flex-wrap': 'wrap',
            gap: 10,
            'justify-content': 'center',
            'margin-bottom': 20,
          }}
        >
          <ControlButton
            label="Info"
            color="#3b82f6"
            onClick={() =>
              emit(NotifyInfo, {
                title: 'Information',
                message: 'This is an informational notification that will auto-dismiss in 5 seconds.',
              })
            }
          />
          <ControlButton
            label="Success"
            color="#22c55e"
            onClick={() =>
              emit(NotifySuccess, {
                title: 'Success!',
                message: 'Operation completed successfully. This dismisses in 5 seconds.',
              })
            }
          />
          <ControlButton
            label="Warning"
            color="#f59e0b"
            onClick={() =>
              emit(NotifyWarning, {
                title: 'Warning',
                message: 'Something needs your attention. This stays for 10 seconds.',
              })
            }
          />
          <ControlButton
            label="Error"
            color="#ef4444"
            onClick={() =>
              emit(NotifyError, {
                title: 'Error',
                message: 'Something went wrong! This notification stays until dismissed manually.',
              })
            }
          />
          <ControlButton
            label="Flood (20)"
            color="#8b5cf6"
            onClick={handleFlood}
          />
          <ControlButton
            label="Dismiss All"
            color="#64748b"
            onClick={() => emit(DismissAll, undefined)}
          />
        </div>

        {/* Stats */}
        <div style={{ color: '#475569', 'font-size': 13 }}>
          Active: {count}
          {queuedCount > 0 && (
            <span style={{ 'margin-left': 12 }}>
              Queued: {queuedCount}
            </span>
          )}
        </div>
      </div>

      {/* Notification stack (top-right) */}
      <div
        style={{
          position: 'fixed',
          top: 20,
          right: 20,
          'z-index': 1000,
          display: 'flex',
          'flex-direction': 'column',
        }}
      >
        {visibleNotifications.map((notif, i) => (
          <NotificationItem
            notif={notif}
            index={i}
            onDismiss={handleDismiss}
          />
        ))}
        {queuedCount > 0 && (
          <div
            style={{
              'text-align': 'center',
              color: '#475569',
              'font-size': 12,
              'margin-top': 4,
            }}
          >
            +{queuedCount} more queued
          </div>
        )}
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// ControlButton
// ---------------------------------------------------------------------------

function ControlButton({
  label,
  color,
  onClick,
}: {
  label: string
  color: string
  onClick: () => void
}) {
  return (
    <button
      onClick={onClick}
      style={{
        padding: '10px 20px',
        'border-radius': 10,
        border: `1px solid ${color}40`,
        background: `${color}20`,
        color: color,
        'font-size': 14,
        'font-weight': 600,
        cursor: 'pointer',
        transition: 'all 0.2s',
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.background = `${color}35`
        e.currentTarget.style.transform = 'translateY(-1px)'
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.background = `${color}20`
        e.currentTarget.style.transform = 'translateY(0)'
      }}
    >
      {label}
    </button>
  )
}

// examples/solid/drag-api-animation/src/App.tsx
import { onMount } from 'solid-js'
import { usePulse, useEmit } from '@pulse/solid'
import {
  CardsChanged,
  DragStateChanged,
  DragPositionChanged,
  CardStatusesChanged,
  DragStart,
  DragMove,
  DragEnd,
  CardMoved,
  UndoRequested,
  type KanbanCard,
  type ColumnId,
  type CardStatus,
} from './engine'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const COLUMNS: { id: ColumnId; title: string; color: string }[] = [
  { id: 'todo', title: 'Todo', color: '#4361ee' },
  { id: 'in-progress', title: 'In Progress', color: '#f59e0b' },
  { id: 'done', title: 'Done', color: '#10b981' },
]

const PRIORITY_COLORS: Record<string, string> = {
  low: '#10b981',
  medium: '#f59e0b',
  high: '#ef4444',
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = {
  container: {
    'min-height': '100vh',
    background: '#0f172a',
    padding: '32px 24px',
    'font-family':
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  header: {
    'text-align': 'center' as const,
    'margin-bottom': 32,
  },
  title: {
    'font-size': 36,
    'font-weight': 800,
    color: '#f1f5f9',
    margin: 0,
  },
  subtitle: {
    color: '#94a3b8',
    'font-size': 14,
    'margin-top': 6,
  },
  board: {
    display: 'grid',
    'grid-template-columns': 'repeat(3, 1fr)',
    gap: 20,
    'max-width': 1100,
    margin: '0 auto',
  },
  column: (color: string) =>
    ({
      background: '#1e293b',
      'border-radius': 16,
      padding: 16,
      'min-height': 400,
      'border-top': `3px solid ${color}`,
    }),
  columnHeader: {
    display: 'flex',
    'align-items': 'center',
    'justify-content': 'space-between',
    'margin-bottom': 16,
    padding: '0 4px',
  },
  columnTitle: {
    'font-size': 16,
    'font-weight': 700,
    color: '#e2e8f0',
  },
  columnCount: (color: string) =>
    ({
      'font-size': 13,
      'font-weight': 600,
      color: color,
      background: `${color}22`,
      padding: '2px 10px',
      'border-radius': 12,
    }),
  card: (status: CardStatus, isDragging: boolean) => {
    let borderColor = '#334155'
    let bg = '#0f172a'
    if (status === 'saving') {
      borderColor = '#f59e0b'
    } else if (status === 'saved') {
      borderColor = '#10b981'
      bg = '#10b98108'
    } else if (status === 'error') {
      borderColor = '#ef4444'
      bg = '#ef444408'
    }
    return {
      background: bg,
      border: `2px solid ${borderColor}`,
      'border-radius': 12,
      padding: 16,
      'margin-bottom': 10,
      cursor: isDragging ? 'grabbing' : 'grab',
      opacity: isDragging ? 0.4 : 1,
      transition: 'border-color 0.3s, background 0.3s, opacity 0.15s',
      'user-select': 'none' as const,
    }
  },
  cardTitle: {
    'font-size': 15,
    'font-weight': 600,
    color: '#e2e8f0',
    margin: 0,
    'margin-bottom': 4,
  },
  cardDesc: {
    'font-size': 13,
    color: '#94a3b8',
    margin: 0,
    'margin-bottom': 10,
  },
  cardFooter: {
    display: 'flex',
    'align-items': 'center',
    'justify-content': 'space-between',
  },
  priorityBadge: (priority: string) =>
    ({
      'font-size': 11,
      'font-weight': 600,
      'text-transform': 'uppercase' as const,
      color: PRIORITY_COLORS[priority] ?? '#94a3b8',
      background: `${PRIORITY_COLORS[priority] ?? '#94a3b8'}22`,
      padding: '2px 8px',
      'border-radius': 8,
    }),
  statusBadge: (status: CardStatus) => {
    const map: Record<CardStatus, { color: string; label: string }> = {
      idle: { color: '#64748b', label: '' },
      saving: { color: '#f59e0b', label: 'Saving...' },
      saved: { color: '#10b981', label: 'Saved' },
      error: { color: '#ef4444', label: 'Error - retrying' },
      settled: { color: '#64748b', label: '' },
    }
    const info = map[status]
    if (!info.label) return { display: 'none' }
    return {
      'font-size': 11,
      'font-weight': 600,
      color: info.color,
    }
  },
  undoBtn: {
    'font-size': 12,
    color: '#94a3b8',
    background: 'none',
    border: '1px solid #334155',
    'border-radius': 6,
    padding: '2px 8px',
    cursor: 'pointer',
    'margin-left': 8,
  },
  ghostCard: {
    position: 'fixed' as const,
    'pointer-events': 'none' as const,
    'z-index': 1000,
    width: 300,
    background: '#1e293b',
    border: '2px solid #4361ee',
    'border-radius': 12,
    padding: 16,
    'box-shadow': '0 20px 40px rgba(0,0,0,0.5)',
  },
  dropZone: {
    'min-height': 60,
    border: '2px dashed transparent',
    'border-radius': 8,
    transition: 'border-color 0.2s, background 0.2s',
    background: 'transparent',
  },
}

// ---------------------------------------------------------------------------
// CardComponent
// ---------------------------------------------------------------------------

function KanbanCardComponent({ card }: { card: KanbanCard }) {
  const emit = useEmit()
  const drag = usePulse(DragStateChanged, null as ReturnType<typeof DragStateChanged['__type']> | null)
  const statuses = usePulse(CardStatusesChanged, {} as Record<string, CardStatus>)
  let cardRef = null

  const status: CardStatus = statuses()[card.id] ?? 'idle'
  const isDragging = drag()?.cardId === card.id

  const statusLabels: Record<CardStatus, string> = {
    idle: '',
    saving: 'Saving...',
    saved: 'Saved',
    error: 'Error - retrying',
    settled: '',
  }

  const handleMouseDown = 
    (e: MouseEvent) => {
      e.preventDefault()
      const rect = cardRef?.getBoundingClientRect()
      if (!rect) return
      emit(DragStart, {
        cardId: card.id,
        startX: e.clientX,
        startY: e.clientY,
        offsetX: e.clientX - rect.left,
        offsetY: e.clientY - rect.top,
      })
    }
  return (
    <div
      ref={cardRef}
      style={{
        ...styles.card(status, isDragging),
        animation:
          status === 'error'
            ? 'shake 0.5s ease-in-out'
            : status === 'saved'
              ? 'flashGreen 0.6s ease-out'
              : undefined,
      }}
      onMouseDown={handleMouseDown}
    >
      <p style={styles.cardTitle}>{card.title}</p>
      <p style={styles.cardDesc}>{card.description}</p>
      <div style={styles.cardFooter}>
        <span style={styles.priorityBadge(card.priority)}>{card.priority}</span>
        <span>
          <span style={styles.statusBadge(status)}>{statusLabels[status]}</span>
          {(status === 'saved' || status === 'error') && (
            <button
              style={styles.undoBtn}
              onClick={(e) => {
                e.stopPropagation()
                emit(UndoRequested, card.id)
              }}
            >
              Undo
            </button>
          )}
        </span>
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Ghost card
// ---------------------------------------------------------------------------

function GhostCard() {
  const drag = usePulse(DragStateChanged, null as any)
  const allCards = usePulse(CardsChanged, [] as KanbanCard[])
  const springPos = usePulse(DragPositionChanged, { x: 0, y: 0 })

  if (!drag()) return null

  const card = allCards().find((c) => c.id === drag().cardId)
  if (!card) return null

  return (
    <div
      style={{
        ...styles.ghostCard,
        left: springPos.x - drag().offsetX,
        top: springPos.y - drag().offsetY,
      }}
    >
      <p style={styles.cardTitle}>{card.title}</p>
      <p style={styles.cardDesc}>{card.description}</p>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Column
// ---------------------------------------------------------------------------

function Column({
  id,
  title,
  color,
}: {
  id: ColumnId
  title: string
  color: string
}) {
  const allCards = usePulse(CardsChanged, [] as KanbanCard[])
  const drag = usePulse(DragStateChanged, null as any)
  const emit = useEmit()

  const columnCards = allCards().filter((c) => c.column === id)
  const isDragging = drag() !== null

  return (
    <div style={styles.column(color)}>
      <div style={styles.columnHeader}>
        <span style={styles.columnTitle}>{title}</span>
        <span style={styles.columnCount(color)}>{columnCards.length}</span>
      </div>
      {columnCards.map((card) => (
        <KanbanCardComponent card={card} />
      ))}
      {isDragging && (
        <div
          style={styles.dropZone}
          onMouseEnter={(e) => {
            e.currentTarget.style.borderColor = '#4361ee'
            e.currentTarget.style.background = '#4361ee11'
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.borderColor = 'transparent'
            e.currentTarget.style.background = 'transparent'
          }}
          onMouseUp={() => {
            if (drag()) {
              const card = allCards().find((c) => c.id === drag().cardId)
              if (card && card.column !== id) {
                emit(CardMoved, {
                  cardId: drag.cardId,
                  fromColumn: card.column,
                  toColumn: id,
                })
              }
              emit(DragEnd, undefined)
            }
          }}
        >
          <div
            style={{
              padding: 20,
              'text-align': 'center',
              color: '#475569',
              'font-size': 13,
            }}
          >
            Drop here
          </div>
        </div>
      )}
    </div>
  )
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

export default function App() {
  const emit = useEmit()
  const drag = usePulse(DragStateChanged, null as any)

  // Global mouse move/up handlers for drag()
  onMount(() => {
    const handleMouseMove = (e: MouseEvent) => {
      if (drag()) {
        emit(DragMove, { x: e.clientX, y: e.clientY })
      }
    }

    const handleMouseUp = () => {
      if (drag()) {
        emit(DragEnd, undefined)
      }
    }

    window.addEventListener('mousemove', handleMouseMove)
    window.addEventListener('mouseup', handleMouseUp)
    return () => {
      window.removeEventListener('mousemove', handleMouseMove)
      window.removeEventListener('mouseup', handleMouseUp)
    }
  })

  return (
    <div style={styles.container}>
      {/* Animations */}
      <style>{`
        @keyframes shake {
          0%, 100% { transform: translateX(0); }
          10%, 30%, 50%, 70%, 90% { transform: translateX(-4px); }
          20%, 40%, 60%, 80% { transform: translateX(4px); }
        }
        @keyframes flashGreen {
          0% { background: #10b98122; }
          100% { background: #0f172a; }
        }
      `}</style>

      <div style={styles.header}>
        <h1 style={styles.title}>Pulse Kanban</h1>
        <p style={styles.subtitle}>
          Drag cards between columns. Spring physics follow your mouse.
          Saves auto-retry on failure.
        </p>
      </div>

      <div style={styles.board}>
        {COLUMNS.map((col) => (
          <Column id={col.id} title={col.title} color={col.color} />
        ))}
      </div>

      <GhostCard />
    </div>
  )
}
