// examples/solid/drag-api-animation/src/App.tsx
import { onMount } from 'solid-js'
import { usePulse, useEmit } from '@pulse/solid'
import {
  CardsChanged,
  DragStateChanged,
  DragPositionChanged,
  CardStatusesChanged,
  DragStart,
  DragMove,
  DragEnd,
  CardMoved,
  UndoRequested,
  type KanbanCard,
  type ColumnId,
  type CardStatus,
} from './engine'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const COLUMNS: { id: ColumnId; title: string; color: string }[] = [
  { id: 'todo', title: 'Todo', color: '#4361ee' },
  { id: 'in-progress', title: 'In Progress', color: '#f59e0b' },
  { id: 'done', title: 'Done', color: '#10b981' },
]

const PRIORITY_COLORS: Record<string, string> = {
  low: '#10b981',
  medium: '#f59e0b',
  high: '#ef4444',
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = {
  container: {
    'min-height': '100vh',
    background: '#0f172a',
    padding: '32px 24px',
    'font-family':
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  header: {
    'text-align': 'center' as const,
    'margin-bottom': 32,
  },
  title: {
    'font-size': 36,
    'font-weight': 800,
    color: '#f1f5f9',
    margin: 0,
  },
  subtitle: {
    color: '#94a3b8',
    'font-size': 14,
    'margin-top': 6,
  },
  board: {
    display: 'grid',
    'grid-template-columns': 'repeat(3, 1fr)',
    gap: 20,
    'max-width': 1100,
    margin: '0 auto',
  },
  column: (color: string) =>
    ({
      background: '#1e293b',
      'border-radius': 16,
      padding: 16,
      'min-height': 400,
      'border-top': `3px solid ${color}`,
    }),
  columnHeader: {
    display: 'flex',
    'align-items': 'center',
    'justify-content': 'space-between',
    'margin-bottom': 16,
    padding: '0 4px',
  },
  columnTitle: {
    'font-size': 16,
    'font-weight': 700,
    color: '#e2e8f0',
  },
  columnCount: (color: string) =>
    ({
      'font-size': 13,
      'font-weight': 600,
      color: color,
      background: `${color}22`,
      padding: '2px 10px',
      'border-radius': 12,
    }),
  card: (status: CardStatus, isDragging: boolean) => {
    let borderColor = '#334155'
    let bg = '#0f172a'
    if (status === 'saving') {
      borderColor = '#f59e0b'
    } else if (status === 'saved') {
      borderColor = '#10b981'
      bg = '#10b98108'
    } else if (status === 'error') {
      borderColor = '#ef4444'
      bg = '#ef444408'
    }
    return {
      background: bg,
      border: `2px solid ${borderColor}`,
      'border-radius': 12,
      padding: 16,
      'margin-bottom': 10,
      cursor: isDragging ? 'grabbing' : 'grab',
      opacity: isDragging ? 0.4 : 1,
      transition: 'border-color 0.3s, background 0.3s, opacity 0.15s',
      'user-select': 'none' as const,
    }
  },
  cardTitle: {
    'font-size': 15,
    'font-weight': 600,
    color: '#e2e8f0',
    margin: 0,
    'margin-bottom': 4,
  },
  cardDesc: {
    'font-size': 13,
    color: '#94a3b8',
    margin: 0,
    'margin-bottom': 10,
  },
  cardFooter: {
    display: 'flex',
    'align-items': 'center',
    'justify-content': 'space-between',
  },
  priorityBadge: (priority: string) =>
    ({
      'font-size': 11,
      'font-weight': 600,
      'text-transform': 'uppercase' as const,
      color: PRIORITY_COLORS[priority] ?? '#94a3b8',
      background: `${PRIORITY_COLORS[priority] ?? '#94a3b8'}22`,
      padding: '2px 8px',
      'border-radius': 8,
    }),
  statusBadge: (status: CardStatus) => {
    const map: Record<CardStatus, { color: string; label: string }> = {
      idle: { color: '#64748b', label: '' },
      saving: { color: '#f59e0b', label: 'Saving...' },
      saved: { color: '#10b981', label: 'Saved' },
      error: { color: '#ef4444', label: 'Error - retrying' },
      settled: { color: '#64748b', label: '' },
    }
    const info = map[status]
    if (!info.label) return { display: 'none' }
    return {
      'font-size': 11,
      'font-weight': 600,
      color: info.color,
    }
  },
  undoBtn: {
    'font-size': 12,
    color: '#94a3b8',
    background: 'none',
    border: '1px solid #334155',
    'border-radius': 6,
    padding: '2px 8px',
    cursor: 'pointer',
    'margin-left': 8,
  },
  ghostCard: {
    position: 'fixed' as const,
    'pointer-events': 'none' as const,
    'z-index': 1000,
    width: 300,
    background: '#1e293b',
    border: '2px solid #4361ee',
    'border-radius': 12,
    padding: 16,
    'box-shadow': '0 20px 40px rgba(0,0,0,0.5)',
  },
  dropZone: {
    'min-height': 60,
    border: '2px dashed transparent',
    'border-radius': 8,
    transition: 'border-color 0.2s, background 0.2s',
    background: 'transparent',
  },
}

// ---------------------------------------------------------------------------
// CardComponent
// ---------------------------------------------------------------------------

function KanbanCardComponent({ card }: { card: KanbanCard }) {
  const emit = useEmit()
  const drag = usePulse(DragStateChanged, null as ReturnType<typeof DragStateChanged['__type']> | null)
  const statuses = usePulse(CardStatusesChanged, {} as Record<string, CardStatus>)
  let cardRef = null

  const status: CardStatus = statuses()[card.id] ?? 'idle'
  const isDragging = drag()?.cardId === card.id

  const statusLabels: Record<CardStatus, string> = {
    idle: '',
    saving: 'Saving...',
    saved: 'Saved',
    error: 'Error - retrying',
    settled: '',
  }

  const handleMouseDown = 
    (e: MouseEvent) => {
      e.preventDefault()
      const rect = cardRef?.getBoundingClientRect()
      if (!rect) return
      emit(DragStart, {
        cardId: card.id,
        startX: e.clientX,
        startY: e.clientY,
        offsetX: e.clientX - rect.left,
        offsetY: e.clientY - rect.top,
      })
    }
  return (
    <div
      ref={cardRef}
      style={{
        ...styles.card(status, isDragging),
        animation:
          status === 'error'
            ? 'shake 0.5s ease-in-out'
            : status === 'saved'
              ? 'flashGreen 0.6s ease-out'
              : undefined,
      }}
      onMouseDown={handleMouseDown}
    >
      <p style={styles.cardTitle}>{card.title}</p>
      <p style={styles.cardDesc}>{card.description}</p>
      <div style={styles.cardFooter}>
        <span style={styles.priorityBadge(card.priority)}>{card.priority}</span>
        <span>
          <span style={styles.statusBadge(status)}>{statusLabels[status]}</span>
          {(status === 'saved' || status === 'error') && (
            <button
              style={styles.undoBtn}
              onClick={(e) => {
                e.stopPropagation()
                emit(UndoRequested, card.id)
              }}
            >
              Undo
            </button>
          )}
        </span>
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Ghost card
// ---------------------------------------------------------------------------

function GhostCard() {
  const drag = usePulse(DragStateChanged, null as any)
  const allCards = usePulse(CardsChanged, [] as KanbanCard[])
  const springPos = usePulse(DragPositionChanged, { x: 0, y: 0 })

  if (!drag()) return null

  const card = allCards().find((c) => c.id === drag().cardId)
  if (!card) return null

  return (
    <div
      style={{
        ...styles.ghostCard,
        left: springPos.x - drag().offsetX,
        top: springPos.y - drag().offsetY,
      }}
    >
      <p style={styles.cardTitle}>{card.title}</p>
      <p style={styles.cardDesc}>{card.description}</p>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Column
// ---------------------------------------------------------------------------

function Column({
  id,
  title,
  color,
}: {
  id: ColumnId
  title: string
  color: string
}) {
  const allCards = usePulse(CardsChanged, [] as KanbanCard[])
  const drag = usePulse(DragStateChanged, null as any)
  const emit = useEmit()

  const columnCards = allCards().filter((c) => c.column === id)
  const isDragging = drag() !== null

  return (
    <div style={styles.column(color)}>
      <div style={styles.columnHeader}>
        <span style={styles.columnTitle}>{title}</span>
        <span style={styles.columnCount(color)}>{columnCards.length}</span>
      </div>
      {columnCards.map((card) => (
        <KanbanCardComponent card={card} />
      ))}
      {isDragging && (
        <div
          style={styles.dropZone}
          onMouseEnter={(e) => {
            e.currentTarget.style.borderColor = '#4361ee'
            e.currentTarget.style.background = '#4361ee11'
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.borderColor = 'transparent'
            e.currentTarget.style.background = 'transparent'
          }}
          onMouseUp={() => {
            if (drag()) {
              const card = allCards().find((c) => c.id === drag().cardId)
              if (card && card.column !== id) {
                emit(CardMoved, {
                  cardId: drag.cardId,
                  fromColumn: card.column,
                  toColumn: id,
                })
              }
              emit(DragEnd, undefined)
            }
          }}
        >
          <div
            style={{
              padding: 20,
              'text-align': 'center',
              color: '#475569',
              'font-size': 13,
            }}
          >
            Drop here
          </div>
        </div>
      )}
    </div>
  )
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

export default function App() {
  const emit = useEmit()
  const drag = usePulse(DragStateChanged, null as any)

  // Global mouse move/up handlers for drag()
  onMount(() => {
    const handleMouseMove = (e: MouseEvent) => {
      if (drag()) {
        emit(DragMove, { x: e.clientX, y: e.clientY })
      }
    }

    const handleMouseUp = () => {
      if (drag()) {
        emit(DragEnd, undefined)
      }
    }

    window.addEventListener('mousemove', handleMouseMove)
    window.addEventListener('mouseup', handleMouseUp)
    return () => {
      window.removeEventListener('mousemove', handleMouseMove)
      window.removeEventListener('mouseup', handleMouseUp)
    }
  })

  return (
    <div style={styles.container}>
      {/* Animations */}
      <style>{`
        @keyframes shake {
          0%, 100% { transform: translateX(0); }
          10%, 30%, 50%, 70%, 90% { transform: translateX(-4px); }
          20%, 40%, 60%, 80% { transform: translateX(4px); }
        }
        @keyframes flashGreen {
          0% { background: #10b98122; }
          100% { background: #0f172a; }
        }
      `}</style>

      <div style={styles.header}>
        <h1 style={styles.title}>Pulse Kanban</h1>
        <p style={styles.subtitle}>
          Drag cards between columns. Spring physics follow your mouse.
          Saves auto-retry on failure.
        </p>
      </div>

      <div style={styles.board}>
        {COLUMNS.map((col) => (
          <Column id={col.id} title={col.title} color={col.color} />
        ))}
      </div>

      <GhostCard />
    </div>
  )
}

// examples/react/sortable-grid/src/App.tsx
import { usePulse, useEmit } from '@pulse/react'
import { useCallback, useEffect, useRef } from 'react'
import {
  ItemsChanged,
  DragStateChanged,
  EnteringIdsChanged,
  ExitingIdsChanged,
  DragStart,
  DragMove,
  DragEnd,
  DragOver,
  ShuffleAll,
  AddItem,
  RemoveItem,
  type GridItem,
  type DragState,
} from './engine'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const COLUMNS = 4
const ITEM_SIZE = 120
const GAP = 12

// ---------------------------------------------------------------------------
// GridCard
// ---------------------------------------------------------------------------

function GridCard({
  item,
  index,
  isDragging,
  isOver,
  isEntering,
  isExiting,
}: {
  item: { id: string; color: string; label: string }
  index: number
  isDragging: boolean
  isOver: boolean
  isEntering: boolean
  isExiting: boolean
}) {
  const emit = useEmit()

  const handleMouseDown = useCallback(
    (e: React.MouseEvent) => {
      const rect = e.currentTarget.getBoundingClientRect()
      emit(DragStart, {
        index,
        x: e.clientX,
        y: e.clientY,
        offsetX: e.clientX - rect.left,
        offsetY: e.clientY - rect.top,
      })
    },
    [emit, index],
  )

  const handleMouseEnter = useCallback(() => {
    emit(DragOver, { index })
  }, [emit, index])

  return (
    <div
      onMouseDown={handleMouseDown}
      onMouseEnter={handleMouseEnter}
      style={{
        width: ITEM_SIZE,
        height: ITEM_SIZE,
        borderRadius: 16,
        background: `linear-gradient(135deg, ${item.color}, ${item.color}cc)`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: isDragging ? 'grabbing' : 'grab',
        opacity: isDragging ? 0.3 : isExiting ? 0 : 1,
        transform: isOver && !isDragging
          ? 'scale(0.92)'
          : isEntering
            ? 'scale(1)'
            : isExiting
              ? 'scale(0.5)'
              : 'scale(1)',
        transition: isDragging
          ? 'none'
          : 'transform 0.35s cubic-bezier(0.22, 1, 0.36, 1), opacity 0.3s ease',
        boxShadow: isOver && !isDragging
          ? `0 0 0 3px ${item.color}60, 0 4px 16px rgba(0,0,0,0.2)`
          : '0 4px 12px rgba(0,0,0,0.15)',
        position: 'relative',
        userSelect: 'none',
        animation: isEntering ? 'pop-in 0.4s cubic-bezier(0.22, 1, 0.36, 1)' : 'none',
      }}
    >
      <span
        style={{
          fontSize: 28,
          fontWeight: 800,
          color: 'rgba(255,255,255,0.9)',
          textShadow: '0 2px 4px rgba(0,0,0,0.2)',
        }}
      >
        {item.label}
      </span>

      {/* Remove button on hover (using CSS :hover via wrapper) */}
      <button
        onClick={(e) => {
          e.stopPropagation()
          emit(RemoveItem, index)
        }}
        onMouseDown={(e) => e.stopPropagation()}
        style={{
          position: 'absolute',
          top: 6,
          right: 6,
          width: 22,
          height: 22,
          borderRadius: '50%',
          border: 'none',
          background: 'rgba(0,0,0,0.3)',
          color: 'rgba(255,255,255,0.8)',
          fontSize: 12,
          cursor: 'pointer',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          opacity: 0,
          transition: 'opacity 0.2s',
        }}
        className="remove-btn"
      >
        \u2715
      </button>
    </div>
  )
}

// ---------------------------------------------------------------------------
// DragGhost
// ---------------------------------------------------------------------------

function DragGhost() {
  const ds = usePulse(DragStateChanged, { active: false, dragIndex: -1, overIndex: -1, startX: 0, startY: 0, currentX: 0, currentY: 0, offsetX: 0, offsetY: 0 } as DragState)
  const itemList = usePulse(ItemsChanged, [] as GridItem[])

  if (!ds.active || ds.dragIndex < 0 || ds.dragIndex >= itemList.length) return null

  const item = itemList[ds.dragIndex]

  return (
    <div
      style={{
        position: 'fixed',
        left: ds.currentX - ds.offsetX,
        top: ds.currentY - ds.offsetY,
        width: ITEM_SIZE,
        height: ITEM_SIZE,
        borderRadius: 16,
        background: `linear-gradient(135deg, ${item.color}, ${item.color}cc)`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'grabbing',
        zIndex: 9999,
        pointerEvents: 'none',
        boxShadow: `0 16px 40px rgba(0,0,0,0.35), 0 0 0 2px ${item.color}`,
        transform: 'scale(1.08) rotate(2deg)',
        transition: 'transform 0.15s ease',
      }}
    >
      <span
        style={{
          fontSize: 28,
          fontWeight: 800,
          color: 'rgba(255,255,255,0.9)',
          textShadow: '0 2px 4px rgba(0,0,0,0.2)',
        }}
      >
        {item.label}
      </span>
    </div>
  )
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

export default function App() {
  const emit = useEmit()
  const itemList = usePulse(ItemsChanged, [] as GridItem[])
  const ds = usePulse(DragStateChanged, { active: false, dragIndex: -1, overIndex: -1, startX: 0, startY: 0, currentX: 0, currentY: 0, offsetX: 0, offsetY: 0 } as DragState)
  const entering = usePulse(EnteringIdsChanged, new Set<string>())
  const exiting = usePulse(ExitingIdsChanged, new Set<string>())

  // Global mouse move/up handlers for drag
  useEffect(() => {
    const handleMove = (e: MouseEvent) => {
      if (ds.active) {
        emit(DragMove, { x: e.clientX, y: e.clientY })
      }
    }
    const handleUp = () => {
      if (ds.active) {
        emit(DragEnd, undefined)
      }
    }
    window.addEventListener('mousemove', handleMove)
    window.addEventListener('mouseup', handleUp)
    return () => {
      window.removeEventListener('mousemove', handleMove)
      window.removeEventListener('mouseup', handleUp)
    }
  }, [ds.active, emit])

  return (
    <div
      style={{
        minHeight: '100vh',
        background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0f172a 100%)',
        fontFamily:
          '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        padding: 40,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      }}
    >
      <h1
        style={{
          fontSize: 32,
          fontWeight: 800,
          color: '#f1f5f9',
          marginBottom: 8,
        }}
      >
        Sortable Grid
      </h1>
      <p style={{ color: '#64748b', fontSize: 14, marginBottom: 32 }}>
        Drag items to reorder. Items animate to new positions.
      </p>

      {/* Controls */}
      <div style={{ display: 'flex', gap: 10, marginBottom: 32 }}>
        <button
          onClick={() => emit(ShuffleAll, undefined)}
          style={{
            padding: '10px 24px',
            borderRadius: 10,
            border: '1px solid #6366f140',
            background: '#6366f120',
            color: '#818cf8',
            fontSize: 14,
            fontWeight: 600,
            cursor: 'pointer',
            transition: 'all 0.2s',
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = '#6366f135'
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = '#6366f120'
          }}
        >
          Shuffle All
        </button>
        <button
          onClick={() => emit(AddItem, undefined)}
          style={{
            padding: '10px 24px',
            borderRadius: 10,
            border: '1px solid #22c55e40',
            background: '#22c55e20',
            color: '#4ade80',
            fontSize: 14,
            fontWeight: 600,
            cursor: 'pointer',
            transition: 'all 0.2s',
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = '#22c55e35'
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = '#22c55e20'
          }}
        >
          Add Item
        </button>
      </div>

      {/* Grid */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: `repeat(${COLUMNS}, ${ITEM_SIZE}px)`,
          gap: GAP,
        }}
      >
        {itemList.map((item, index) => (
          <GridCard
            key={item.id}
            item={item}
            index={index}
            isDragging={ds.active && ds.dragIndex === index}
            isOver={ds.active && ds.overIndex === index && ds.dragIndex !== index}
            isEntering={entering.has(item.id)}
            isExiting={exiting.has(item.id)}
          />
        ))}
      </div>

      {/* Drag ghost */}
      <DragGhost />

      {/* Item count */}
      <p style={{ color: '#475569', fontSize: 13, marginTop: 24 }}>
        {itemList.length} items
      </p>

      <style>{`
        @keyframes pop-in {
          from { transform: scale(0); opacity: 0; }
          to { transform: scale(1); opacity: 1; }
        }
        .remove-btn { opacity: 0 !important; }
        div:hover > .remove-btn { opacity: 1 !important; }
      `}</style>
    </div>
  )
}
