// examples/vue/sortable-grid/src/App.vue
<script setup lang="ts">
import { providePulse, useEmit, usePulse } from '@pulse/vue'
import {
  engine,
  COLS,
  CELL_SIZE,
  GAP,
  DragStart,
  DragMove,
  DragEnd,
  ShuffleItems,
  AddItem,
  RemoveItem,
  ItemsChanged,
  DraggingIdChanged,
  GhostPosChanged,
  PositionsChanged,
  getItems,
  getDraggingId,
  getGhostPos,
  getPositions,
} from './engine'

providePulse(engine)

const emit = useEmit()
const itemList = usePulse(ItemsChanged, getItems())
const dragId = usePulse(DraggingIdChanged, getDraggingId())
const ghost = usePulse(GhostPosChanged, getGhostPos())
const pos = usePulse(PositionsChanged, getPositions())

let containerRect: DOMRect | null = null

function onPointerDown(e: PointerEvent, id: number) {
  const container = (e.currentTarget as HTMLElement).closest('[data-grid]') as HTMLElement
  if (container) containerRect = container.getBoundingClientRect()
  const x = e.clientX - (containerRect?.left ?? 0)
  const y = e.clientY - (containerRect?.top ?? 0)
  emit(DragStart, { id, x, y })
  ;(e.target as HTMLElement).setPointerCapture(e.pointerId)
}

function onPointerMove(e: PointerEvent) {
  if (dragId.value < 0) return
  const x = e.clientX - (containerRect?.left ?? 0)
  const y = e.clientY - (containerRect?.top ?? 0)
  emit(DragMove, { x, y })
}

function onPointerUp() {
  if (dragId.value < 0) return
  emit(DragEnd, undefined)
}

const gridWidth = COLS * (CELL_SIZE + GAP)
</script>

<template>
  <div :style="{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '24px' }">
    <h1 :style="{ color: '#fff', fontSize: '28px', fontWeight: 300, letterSpacing: '2px' }">Sortable Grid</h1>

    <div :style="{ display: 'flex', gap: '12px' }">
      <button @click="emit(ShuffleItems, undefined)" :style="{
        background: 'rgba(255,255,255,0.1)', border: '1px solid rgba(255,255,255,0.2)',
        color: '#fff', padding: '8px 20px', borderRadius: '8px', cursor: 'pointer', fontSize: '13px',
      }">Shuffle</button>
      <button @click="emit(AddItem, undefined)" :style="{
        background: 'rgba(0,184,148,0.2)', border: '1px solid rgba(0,184,148,0.4)',
        color: '#00b894', padding: '8px 20px', borderRadius: '8px', cursor: 'pointer', fontSize: '13px',
      }">+ Add</button>
    </div>

    <div
      data-grid
      @pointermove="onPointerMove"
      @pointerup="onPointerUp"
      :style="{
        width: `${gridWidth}px`,
        height: `${Math.ceil(itemList.length / COLS) * (CELL_SIZE + GAP)}px`,
        position: 'relative',
        userSelect: 'none',
      }"
    >
      <div
        v-for="(item, i) in itemList"
        :key="item.id"
        @pointerdown="(e) => onPointerDown(e, item.id)"
        :style="{
          position: 'absolute',
          left: `${pos.x[i] ?? 0}px`,
          top: `${pos.y[i] ?? 0}px`,
          width: `${CELL_SIZE}px`,
          height: `${CELL_SIZE}px`,
          background: `linear-gradient(145deg, ${item.color}cc, ${item.color}88)`,
          borderRadius: '12px',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '8px',
          cursor: dragId === item.id ? 'grabbing' : 'grab',
          opacity: dragId === item.id ? 0.5 : 1,
          boxShadow: `0 4px 16px ${item.color}44`,
          border: '1px solid rgba(255,255,255,0.1)',
          transition: 'left 0.2s ease-out, top 0.2s ease-out',
        }"
      >
        <div :style="{ color: '#fff', fontSize: '14px', fontWeight: 600 }">{{ item.label }}</div>
        <button
          @click.stop="emit(RemoveItem, item.id)"
          :style="{
            background: 'rgba(0,0,0,0.2)', border: 'none', color: 'rgba(255,255,255,0.5)',
            width: '20px', height: '20px', borderRadius: '50%', cursor: 'pointer', fontSize: '12px',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }"
        >&times;</button>
      </div>

      <!-- Ghost element -->
      <div
        v-if="dragId >= 0"
        :style="{
          position: 'fixed',
          left: `${ghost.x - CELL_SIZE / 2}px`,
          top: `${ghost.y - CELL_SIZE / 2}px`,
          width: `${CELL_SIZE}px`,
          height: `${CELL_SIZE}px`,
          background: 'rgba(67,97,238,0.3)',
          borderRadius: '12px',
          border: '2px dashed rgba(67,97,238,0.6)',
          pointerEvents: 'none',
          zIndex: 100,
        }"
      />
    </div>

    <p :style="{ color: 'rgba(255,255,255,0.4)', fontSize: '13px' }">
      Drag items to reorder &middot; {{ itemList.length }} items
    </p>
  </div>
</template>

// examples/react/sortable-grid/src/App.tsx
import { usePulse, useEmit } from '@pulse/react'
import { useCallback, useEffect, useRef } from 'react'
import {
  ItemsChanged,
  DragStateChanged,
  EnteringIdsChanged,
  ExitingIdsChanged,
  DragStart,
  DragMove,
  DragEnd,
  DragOver,
  ShuffleAll,
  AddItem,
  RemoveItem,
  type GridItem,
  type DragState,
} from './engine'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const COLUMNS = 4
const ITEM_SIZE = 120
const GAP = 12

// ---------------------------------------------------------------------------
// GridCard
// ---------------------------------------------------------------------------

function GridCard({
  item,
  index,
  isDragging,
  isOver,
  isEntering,
  isExiting,
}: {
  item: { id: string; color: string; label: string }
  index: number
  isDragging: boolean
  isOver: boolean
  isEntering: boolean
  isExiting: boolean
}) {
  const emit = useEmit()

  const handleMouseDown = useCallback(
    (e: React.MouseEvent) => {
      const rect = e.currentTarget.getBoundingClientRect()
      emit(DragStart, {
        index,
        x: e.clientX,
        y: e.clientY,
        offsetX: e.clientX - rect.left,
        offsetY: e.clientY - rect.top,
      })
    },
    [emit, index],
  )

  const handleMouseEnter = useCallback(() => {
    emit(DragOver, { index })
  }, [emit, index])

  return (
    <div
      onMouseDown={handleMouseDown}
      onMouseEnter={handleMouseEnter}
      style={{
        width: ITEM_SIZE,
        height: ITEM_SIZE,
        borderRadius: 16,
        background: `linear-gradient(135deg, ${item.color}, ${item.color}cc)`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: isDragging ? 'grabbing' : 'grab',
        opacity: isDragging ? 0.3 : isExiting ? 0 : 1,
        transform: isOver && !isDragging
          ? 'scale(0.92)'
          : isEntering
            ? 'scale(1)'
            : isExiting
              ? 'scale(0.5)'
              : 'scale(1)',
        transition: isDragging
          ? 'none'
          : 'transform 0.35s cubic-bezier(0.22, 1, 0.36, 1), opacity 0.3s ease',
        boxShadow: isOver && !isDragging
          ? `0 0 0 3px ${item.color}60, 0 4px 16px rgba(0,0,0,0.2)`
          : '0 4px 12px rgba(0,0,0,0.15)',
        position: 'relative',
        userSelect: 'none',
        animation: isEntering ? 'pop-in 0.4s cubic-bezier(0.22, 1, 0.36, 1)' : 'none',
      }}
    >
      <span
        style={{
          fontSize: 28,
          fontWeight: 800,
          color: 'rgba(255,255,255,0.9)',
          textShadow: '0 2px 4px rgba(0,0,0,0.2)',
        }}
      >
        {item.label}
      </span>

      {/* Remove button on hover (using CSS :hover via wrapper) */}
      <button
        onClick={(e) => {
          e.stopPropagation()
          emit(RemoveItem, index)
        }}
        onMouseDown={(e) => e.stopPropagation()}
        style={{
          position: 'absolute',
          top: 6,
          right: 6,
          width: 22,
          height: 22,
          borderRadius: '50%',
          border: 'none',
          background: 'rgba(0,0,0,0.3)',
          color: 'rgba(255,255,255,0.8)',
          fontSize: 12,
          cursor: 'pointer',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          opacity: 0,
          transition: 'opacity 0.2s',
        }}
        className="remove-btn"
      >
        \u2715
      </button>
    </div>
  )
}

// ---------------------------------------------------------------------------
// DragGhost
// ---------------------------------------------------------------------------

function DragGhost() {
  const ds = usePulse(DragStateChanged, { active: false, dragIndex: -1, overIndex: -1, startX: 0, startY: 0, currentX: 0, currentY: 0, offsetX: 0, offsetY: 0 } as DragState)
  const itemList = usePulse(ItemsChanged, [] as GridItem[])

  if (!ds.active || ds.dragIndex < 0 || ds.dragIndex >= itemList.length) return null

  const item = itemList[ds.dragIndex]

  return (
    <div
      style={{
        position: 'fixed',
        left: ds.currentX - ds.offsetX,
        top: ds.currentY - ds.offsetY,
        width: ITEM_SIZE,
        height: ITEM_SIZE,
        borderRadius: 16,
        background: `linear-gradient(135deg, ${item.color}, ${item.color}cc)`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'grabbing',
        zIndex: 9999,
        pointerEvents: 'none',
        boxShadow: `0 16px 40px rgba(0,0,0,0.35), 0 0 0 2px ${item.color}`,
        transform: 'scale(1.08) rotate(2deg)',
        transition: 'transform 0.15s ease',
      }}
    >
      <span
        style={{
          fontSize: 28,
          fontWeight: 800,
          color: 'rgba(255,255,255,0.9)',
          textShadow: '0 2px 4px rgba(0,0,0,0.2)',
        }}
      >
        {item.label}
      </span>
    </div>
  )
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

export default function App() {
  const emit = useEmit()
  const itemList = usePulse(ItemsChanged, [] as GridItem[])
  const ds = usePulse(DragStateChanged, { active: false, dragIndex: -1, overIndex: -1, startX: 0, startY: 0, currentX: 0, currentY: 0, offsetX: 0, offsetY: 0 } as DragState)
  const entering = usePulse(EnteringIdsChanged, new Set<string>())
  const exiting = usePulse(ExitingIdsChanged, new Set<string>())

  // Global mouse move/up handlers for drag
  useEffect(() => {
    const handleMove = (e: MouseEvent) => {
      if (ds.active) {
        emit(DragMove, { x: e.clientX, y: e.clientY })
      }
    }
    const handleUp = () => {
      if (ds.active) {
        emit(DragEnd, undefined)
      }
    }
    window.addEventListener('mousemove', handleMove)
    window.addEventListener('mouseup', handleUp)
    return () => {
      window.removeEventListener('mousemove', handleMove)
      window.removeEventListener('mouseup', handleUp)
    }
  }, [ds.active, emit])

  return (
    <div
      style={{
        minHeight: '100vh',
        background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0f172a 100%)',
        fontFamily:
          '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        padding: 40,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      }}
    >
      <h1
        style={{
          fontSize: 32,
          fontWeight: 800,
          color: '#f1f5f9',
          marginBottom: 8,
        }}
      >
        Sortable Grid
      </h1>
      <p style={{ color: '#64748b', fontSize: 14, marginBottom: 32 }}>
        Drag items to reorder. Items animate to new positions.
      </p>

      {/* Controls */}
      <div style={{ display: 'flex', gap: 10, marginBottom: 32 }}>
        <button
          onClick={() => emit(ShuffleAll, undefined)}
          style={{
            padding: '10px 24px',
            borderRadius: 10,
            border: '1px solid #6366f140',
            background: '#6366f120',
            color: '#818cf8',
            fontSize: 14,
            fontWeight: 600,
            cursor: 'pointer',
            transition: 'all 0.2s',
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = '#6366f135'
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = '#6366f120'
          }}
        >
          Shuffle All
        </button>
        <button
          onClick={() => emit(AddItem, undefined)}
          style={{
            padding: '10px 24px',
            borderRadius: 10,
            border: '1px solid #22c55e40',
            background: '#22c55e20',
            color: '#4ade80',
            fontSize: 14,
            fontWeight: 600,
            cursor: 'pointer',
            transition: 'all 0.2s',
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = '#22c55e35'
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = '#22c55e20'
          }}
        >
          Add Item
        </button>
      </div>

      {/* Grid */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: `repeat(${COLUMNS}, ${ITEM_SIZE}px)`,
          gap: GAP,
        }}
      >
        {itemList.map((item, index) => (
          <GridCard
            key={item.id}
            item={item}
            index={index}
            isDragging={ds.active && ds.dragIndex === index}
            isOver={ds.active && ds.overIndex === index && ds.dragIndex !== index}
            isEntering={entering.has(item.id)}
            isExiting={exiting.has(item.id)}
          />
        ))}
      </div>

      {/* Drag ghost */}
      <DragGhost />

      {/* Item count */}
      <p style={{ color: '#475569', fontSize: 13, marginTop: 24 }}>
        {itemList.length} items
      </p>

      <style>{`
        @keyframes pop-in {
          from { transform: scale(0); opacity: 0; }
          to { transform: scale(1); opacity: 1; }
        }
        .remove-btn { opacity: 0 !important; }
        div:hover > .remove-btn { opacity: 1 !important; }
      `}</style>
    </div>
  )
}
