// examples/solid/3d-morphing-grid/src/App.tsx
import { For } from 'solid-js'
import { useEmit, useSignal, useTween } from '@pulse/solid'
import type { Signal, TweenValue, EventType } from '@pulse/core'
import { engine } from './engine'

/* ------------------------------------------------------------------ */
/*  Shape definitions                                                 */
/* ------------------------------------------------------------------ */

type ShapeMode = 'flat' | 'sphere' | 'wave' | 'spiral'
const MODES: ShapeMode[] = ['flat', 'sphere', 'wave', 'spiral']
const GRID = 4
const TOTAL = GRID * GRID

function getTargetPosition(mode: ShapeMode, row: number, col: number, time: number): { x: number; y: number; z: number } {
  const cx = (col - (GRID - 1) / 2) * 80
  const cy = (row - (GRID - 1) / 2) * 80

  switch (mode) {
    case 'flat':
      return { x: cx, y: cy, z: 0 }
    case 'sphere': {
      const theta = (col / (GRID - 1)) * Math.PI
      const phi = (row / (GRID - 1)) * Math.PI
      const r = 150
      return {
        x: r * Math.sin(phi) * Math.cos(theta),
        y: r * Math.cos(phi),
        z: r * Math.sin(phi) * Math.sin(theta) - r / 2,
      }
    }
    case 'wave':
      return { x: cx, y: cy, z: Math.sin((col + row) * 0.8 + time * 0.002) * 80 }
    case 'spiral': {
      const idx = row * GRID + col
      const angle = idx * 0.5
      const r2 = 40 + idx * 12
      return {
        x: Math.cos(angle) * r2,
        y: Math.sin(angle) * r2,
        z: idx * 8 - TOTAL * 4,
      }
    }
  }
}

/* ------------------------------------------------------------------ */
/*  Events                                                            */
/* ------------------------------------------------------------------ */

const SetShape = engine.event<ShapeMode>('SetShape')
const ShapeChanged = engine.event<ShapeMode>('ShapeChanged')
const CycleDone = engine.event('CycleDone')
const CycleStart = engine.event('CycleStart')

/* ------------------------------------------------------------------ */
/*  State                                                             */
/* ------------------------------------------------------------------ */

const currentShape: Signal<ShapeMode> = engine.signal(SetShape, 'flat' as ShapeMode, (_prev, mode) => mode)

// Per-cell morph tweens (staggered)
const cellMorphStarts: EventType[] = []
const cellMorphTweens: TweenValue[] = []

for (let i = 0; i < TOTAL; i++) {
  const start = engine.event(`CellMorph_${i}`)
  cellMorphStarts.push(start)

  const done = i === TOTAL - 1 ? ShapeChanged : cellMorphStarts[i + 1]
  cellMorphTweens.push(engine.tween({
    start,
    done,
    from: 0,
    to: 1,
    duration: 300,
    easing: 'easeOutBack',
  }))
}

// When SetShape fires, kick off the stagger
engine.on(SetShape, () => {
  engine.emit(cellMorphStarts[0], undefined)
})

// Auto-cycle: join ShapeChanged + CycleStart -> next shape
let cycleIndex = 0
const autoCycleTween = engine.tween({
  start: CycleStart,
  done: CycleDone,
  from: 0,
  to: 1,
  duration: 2500,
  easing: 'linear',
})

engine.on(CycleDone, () => {
  cycleIndex = (cycleIndex + 1) % MODES.length
  engine.emit(SetShape, MODES[cycleIndex])
})

engine.on(ShapeChanged, () => {
  engine.emit(CycleStart, undefined)
})

// Start the cycle
setTimeout(() => {
  engine.emit(SetShape, 'sphere')
}, 500)

/* ------------------------------------------------------------------ */
/*  Cell colors                                                       */
/* ------------------------------------------------------------------ */

const CELL_COLORS = [
  '#6c5ce7', '#00b894', '#e17055', '#0984e3',
  '#d63031', '#fdcb6e', '#a29bfe', '#00cec9',
  '#ff6b6b', '#54a0ff', '#5f27cd', '#01a3a4',
  '#f368e0', '#ff9f43', '#00d2d3', '#c44569',
]

/* ------------------------------------------------------------------ */
/*  App                                                               */
/* ------------------------------------------------------------------ */

export default function App() {
  const emit = useEmit()
  const shape = useSignal(currentShape)
  const morphValues = cellMorphTweens.map(tw => useTween(tw))

  // Track positions: we store the "from" and "to" positions per cell
  const prevPositions: { x: number; y: number; z: number }[] = Array.from({ length: TOTAL }, () => ({ x: 0, y: 0, z: 0 }))
  const targetPositions: { x: number; y: number; z: number }[] = Array.from({ length: TOTAL }, () => ({ x: 0, y: 0, z: 0 }))

  // Update targets when shape changes
  let currentTime = 0
  engine.on(engine.frame, ({ time }) => { currentTime = time })

  engine.on(SetShape, (mode) => {
    for (let r = 0; r < GRID; r++) {
      for (let c = 0; c < GRID; c++) {
        const idx = r * GRID + c
        prevPositions[idx] = { ...targetPositions[idx] }
        targetPositions[idx] = getTargetPosition(mode, r, c, currentTime)
      }
    }
  })

  // Initialize flat positions
  for (let r = 0; r < GRID; r++) {
    for (let c = 0; c < GRID; c++) {
      const idx = r * GRID + c
      const pos = getTargetPosition('flat', r, c, 0)
      prevPositions[idx] = pos
      targetPositions[idx] = pos
    }
  }

  return (
    <div style={{ display: 'flex', 'flex-direction': 'column', 'align-items': 'center', gap: '32px', 'user-select': 'none' }}>
      <h1 style={{ color: '#fff', 'font-size': '28px', 'font-weight': '300', 'letter-spacing': '2px' }}>
        3D Morphing Grid
      </h1>

      {/* Shape buttons */}
      <div style={{ display: 'flex', gap: '12px' }}>
        <For each={MODES}>
          {(mode) => (
            <button
              onClick={() => { cycleIndex = MODES.indexOf(mode); engine.emit(SetShape, mode) }}
              style={{
                background: shape() === mode ? 'rgba(255,255,255,0.25)' : 'rgba(255,255,255,0.08)',
                border: shape() === mode ? '1px solid rgba(255,255,255,0.5)' : '1px solid rgba(255,255,255,0.15)',
                color: '#fff',
                padding: '8px 20px',
                'border-radius': '20px',
                cursor: 'pointer',
                'font-size': '13px',
                'text-transform': 'capitalize',
                'letter-spacing': '1px',
              }}
            >
              {mode}
            </button>
          )}
        </For>
      </div>

      {/* 3D viewport */}
      <div style={{ perspective: '1000px', width: '500px', height: '500px', position: 'relative' }}>
        <div style={{
          width: '100%', height: '100%',
          'transform-style': 'preserve-3d',
          transform: 'rotateX(-15deg) rotateY(20deg)',
          position: 'relative',
        }}>
          <For each={Array.from({ length: TOTAL }, (_, i) => i)}>
            {(idx) => {
              const t = () => morphValues[idx]()
              const x = () => prevPositions[idx].x + (targetPositions[idx].x - prevPositions[idx].x) * t()
              const y = () => prevPositions[idx].y + (targetPositions[idx].y - prevPositions[idx].y) * t()
              const z = () => prevPositions[idx].z + (targetPositions[idx].z - prevPositions[idx].z) * t()
              const color = CELL_COLORS[idx % CELL_COLORS.length]

              return (
                <div style={{
                  position: 'absolute',
                  left: '50%',
                  top: '50%',
                  width: '60px',
                  height: '60px',
                  'margin-left': '-30px',
                  'margin-top': '-30px',
                  transform: `translate3d(${x()}px, ${y()}px, ${z()}px)`,
                  background: `linear-gradient(145deg, ${color}cc, ${color}66)`,
                  'border-radius': '12px',
                  'box-shadow': `0 4px 16px ${color}44`,
                  border: `1px solid ${color}88`,
                  display: 'flex',
                  'align-items': 'center',
                  'justify-content': 'center',
                  color: '#fff',
                  'font-size': '14px',
                  'font-weight': '600',
                }}>
                  {idx + 1}
                </div>
              )
            }}
          </For>
        </div>
      </div>

      <p style={{ color: 'rgba(255,255,255,0.4)', 'font-size': '13px' }}>
        Auto-cycling shapes &middot; Click buttons to override &middot; Current: {shape()}
      </p>
    </div>
  )
}

// examples/react/3d-morphing-grid/src/App.tsx
import { useCallback } from 'react'
import { useEmit, useSignal, useTween } from '@pulse/react'
import type { EventType, Signal, TweenValue } from '@pulse/core'
import { engine } from './engine'

/* ------------------------------------------------------------------ */
/*  Constants                                                         */
/* ------------------------------------------------------------------ */

const GRID = 4
const CELL_COUNT = GRID * GRID
type Shape = 'flat' | 'sphere' | 'wave' | 'spiral'
const SHAPES: Shape[] = ['flat', 'sphere', 'wave', 'spiral']

/* ------------------------------------------------------------------ */
/*  Shape target calculators                                          */
/* ------------------------------------------------------------------ */

function getShapeTargets(shape: Shape, row: number, col: number): { rotX: number; rotY: number; tz: number; scale: number; radius: number } {
  const cx = (GRID - 1) / 2
  const cy = (GRID - 1) / 2
  const dx = col - cx
  const dy = row - cy
  const dist = Math.sqrt(dx * dx + dy * dy)
  const angle = Math.atan2(dy, dx)
  const maxDist = Math.sqrt(cx * cx + cy * cy)
  const normDist = dist / maxDist

  switch (shape) {
    case 'flat':
      return { rotX: 0, rotY: 0, tz: 0, scale: 1, radius: 8 }
    case 'sphere': {
      const curve = Math.cos(normDist * Math.PI * 0.5)
      return {
        rotX: dy * 15,
        rotY: -dx * 15,
        tz: curve * 120,
        scale: 0.9 + curve * 0.2,
        radius: 50,
      }
    }
    case 'wave': {
      const wave = Math.sin((col / GRID) * Math.PI * 2 + (row / GRID) * Math.PI)
      return {
        rotX: wave * 20,
        rotY: 0,
        tz: wave * 80,
        scale: 0.85 + Math.abs(wave) * 0.3,
        radius: 8,
      }
    }
    case 'spiral': {
      const spiralAngle = angle + normDist * Math.PI * 2
      return {
        rotX: Math.sin(spiralAngle) * 30,
        rotY: Math.cos(spiralAngle) * 30,
        tz: normDist * 100,
        scale: 1 - normDist * 0.3,
        radius: 50 * normDist,
      }
    }
  }
}

/* ------------------------------------------------------------------ */
/*  Cell distance from center (for stagger delay)                     */
/* ------------------------------------------------------------------ */

function cellDistFromCenter(index: number): number {
  const row = Math.floor(index / GRID)
  const col = index % GRID
  const cx = (GRID - 1) / 2
  const cy = (GRID - 1) / 2
  return Math.sqrt((col - cx) ** 2 + (row - cy) ** 2)
}

const maxCellDist = cellDistFromCenter(0) // corner cell

/* ------------------------------------------------------------------ */
/*  Events                                                            */
/* ------------------------------------------------------------------ */

const MorphTrigger = engine.event<Shape>('MorphTrigger')
const AllMorphed = engine.event('AllMorphed')
const AutoCycleToggle = engine.event('AutoCycleToggle')

// Per-cell events
const cellMorphStarts: EventType[] = []
const cellMorphDones: EventType<number>[] = []

for (let i = 0; i < CELL_COUNT; i++) {
  cellMorphStarts.push(engine.event(`CellMorphStart_${i}`))
  cellMorphDones.push(engine.event<number>(`CellMorphDone_${i}`))
}

/* ------------------------------------------------------------------ */
/*  Per-cell tweens (5 properties each)                               */
/* ------------------------------------------------------------------ */

// Current targets (mutated on morph)
const cellTargets: Array<{ rotX: number; rotY: number; tz: number; scale: number; radius: number }> = []
const cellFroms: Array<{ rotX: number; rotY: number; tz: number; scale: number; radius: number }> = []

// Tween arrays: each cell has 5 tweens
const rotXTweens: TweenValue[] = []
const rotYTweens: TweenValue[] = []
const tzTweens: TweenValue[] = []
const scaleTweens: TweenValue[] = []
const radiusTweens: TweenValue[] = []

for (let i = 0; i < CELL_COUNT; i++) {
  cellTargets.push({ rotX: 0, rotY: 0, tz: 0, scale: 1, radius: 8 })
  cellFroms.push({ rotX: 0, rotY: 0, tz: 0, scale: 1, radius: 8 })

  const start = cellMorphStarts[i]
  const done = cellMorphDones[i]

  rotXTweens.push(engine.tween({ start, from: () => cellFroms[i].rotX, to: () => cellTargets[i].rotX, duration: 800, easing: 'easeOutBack' }))
  rotYTweens.push(engine.tween({ start, from: () => cellFroms[i].rotY, to: () => cellTargets[i].rotY, duration: 800, easing: 'easeOutBack' }))
  tzTweens.push(engine.tween({ start, from: () => cellFroms[i].tz, to: () => cellTargets[i].tz, duration: 800, easing: 'easeOutBack' }))
  scaleTweens.push(engine.tween({ start, from: () => cellFroms[i].scale, to: () => cellTargets[i].scale, duration: 800, easing: 'easeOutBack' }))
  radiusTweens.push(engine.tween({ start, done, from: () => cellFroms[i].radius, to: () => cellTargets[i].radius, duration: 800, easing: 'easeOutBack' }))
}

/* ------------------------------------------------------------------ */
/*  Join: all CellMorphDone -> AllMorphed                             */
/* ------------------------------------------------------------------ */

engine.join(cellMorphDones, AllMorphed, {
  do: () => undefined,
})

/* ------------------------------------------------------------------ */
/*  MorphTrigger handler: set targets + stagger cell starts           */
/* ------------------------------------------------------------------ */

engine.on(MorphTrigger, (shape) => {
  for (let i = 0; i < CELL_COUNT; i++) {
    const row = Math.floor(i / GRID)
    const col = i % GRID
    const targets = getShapeTargets(shape, row, col)

    // Save current values as "from"
    cellFroms[i] = {
      rotX: rotXTweens[i].value,
      rotY: rotYTweens[i].value,
      tz: tzTweens[i].value,
      scale: scaleTweens[i].value,
      radius: radiusTweens[i].value,
    }
    cellTargets[i] = targets
  }

  // Stagger: emit cell starts based on distance from center
  for (let i = 0; i < CELL_COUNT; i++) {
    const dist = cellDistFromCenter(i)
    const delay = (dist / maxCellDist) * 300
    setTimeout(() => {
      engine.emit(cellMorphStarts[i], undefined)
    }, delay)
  }
})

/* ------------------------------------------------------------------ */
/*  Current shape signal                                              */
/* ------------------------------------------------------------------ */

const currentShape: Signal<Shape> = engine.signal(MorphTrigger, 'flat' as Shape, (_prev, shape) => shape)

/* ------------------------------------------------------------------ */
/*  Auto-cycle mode                                                   */
/* ------------------------------------------------------------------ */

const autoCycling: Signal<boolean> = engine.signal(AutoCycleToggle, false, (prev) => !prev)

let autoCycleTimer: ReturnType<typeof setTimeout> | null = null

engine.on(AutoCycleToggle, () => {
  // Use setTimeout to read the updated signal
  setTimeout(() => {
    if (autoCycling.value) {
      advanceAutoCycle()
    } else if (autoCycleTimer) {
      clearTimeout(autoCycleTimer)
      autoCycleTimer = null
    }
  }, 0)
})

engine.on(AllMorphed, () => {
  if (autoCycling.value) {
    autoCycleTimer = setTimeout(advanceAutoCycle, 3000)
  }
})

function advanceAutoCycle() {
  const current = currentShape.value
  const idx = SHAPES.indexOf(current)
  const next = SHAPES[(idx + 1) % SHAPES.length]
  engine.emit(MorphTrigger, next)
}

/* ------------------------------------------------------------------ */
/*  Cell component                                                    */
/* ------------------------------------------------------------------ */

function Cell({ index }: { index: number }) {
  const row = Math.floor(index / GRID)
  const col = index % GRID

  const rotX = useTween(rotXTweens[index])
  const rotY = useTween(rotYTweens[index])
  const tz = useTween(tzTweens[index])
  const scale = useTween(scaleTweens[index])
  const radius = useTween(radiusTweens[index])

  // Gradient based on grid position
  const hue1 = (row / GRID) * 120 + (col / GRID) * 60 + 200
  const hue2 = hue1 + 40

  return (
    <div
      style={{
        width: 80,
        height: 80,
        transform: `rotateX(${rotX}deg) rotateY(${rotY}deg) translateZ(${tz}px) scale(${scale})`,
        borderRadius: `${radius}%`,
        background: `linear-gradient(135deg, hsl(${hue1}, 70%, 50%), hsl(${hue2}, 80%, 40%))`,
        boxShadow: `0 ${4 + tz * 0.1}px ${16 + Math.abs(tz) * 0.2}px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.15)`,
        border: '1px solid rgba(255,255,255,0.1)',
      }}
    />
  )
}

/* ------------------------------------------------------------------ */
/*  App                                                               */
/* ------------------------------------------------------------------ */

export default function App() {
  const emit = useEmit()
  const shape = useSignal(currentShape)
  const isAuto = useSignal(autoCycling)

  const triggerShape = useCallback((s: Shape) => {
    emit(MorphTrigger, s)
  }, [emit])

  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 40 }}>
      <h1 style={{ color: '#fff', fontSize: 28, fontWeight: 300, letterSpacing: 2 }}>
        3D Morphing Grid
      </h1>

      <div
        style={{
          perspective: 1500,
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: `repeat(${GRID}, 80px)`,
            gap: 16,
            transformStyle: 'preserve-3d',
            transform: 'rotateX(15deg) rotateY(-10deg)',
          }}
        >
          {Array.from({ length: CELL_COUNT }, (_, i) => (
            <Cell key={i} index={i} />
          ))}
        </div>
      </div>

      <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', justifyContent: 'center' }}>
        {SHAPES.map((s) => (
          <button
            key={s}
            onClick={() => triggerShape(s)}
            style={{
              background: shape === s ? 'rgba(255,255,255,0.2)' : 'rgba(255,255,255,0.05)',
              border: shape === s ? '1px solid rgba(255,255,255,0.4)' : '1px solid rgba(255,255,255,0.15)',
              color: '#fff',
              padding: '10px 24px',
              borderRadius: 8,
              cursor: 'pointer',
              fontSize: 14,
              letterSpacing: 1,
              textTransform: 'capitalize',
              transition: 'all 0.2s',
            }}
          >
            {s}
          </button>
        ))}

        <button
          onClick={() => emit(AutoCycleToggle, undefined)}
          style={{
            background: isAuto ? 'rgba(100,200,255,0.2)' : 'rgba(255,255,255,0.05)',
            border: isAuto ? '1px solid rgba(100,200,255,0.4)' : '1px solid rgba(255,255,255,0.15)',
            color: '#fff',
            padding: '10px 24px',
            borderRadius: 8,
            cursor: 'pointer',
            fontSize: 14,
            letterSpacing: 1,
          }}
        >
          {isAuto ? '\u23F8 Stop Auto' : '\u25B6 Auto Cycle'}
        </button>
      </div>

      <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: 13 }}>
        Current: <span style={{ color: 'rgba(255,255,255,0.7)' }}>{shape}</span>
      </p>
    </div>
  )
}
