// examples/react/collaborative-editor/src/App.js
import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useRef, useCallback } from 'react';
import { useSignal, useEmit } from '@pulse/react';
import { document as docSignal, cursors, activeUsers, editHistory, hasConflict, LocalEdit, CursorMoved, cursorSpringTargets, allUsers, } from './engine';
// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------
const styles = {
    container: {
        display: 'flex',
        height: '100vh',
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        background: '#f5f5f5',
    },
    mainPanel: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
    },
    header: {
        background: '#1a1a2e',
        color: '#fff',
        padding: '12px 20px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 700,
    },
    presenceRow: {
        display: 'flex',
        gap: 8,
        alignItems: 'center',
    },
    avatar: (color, isOnline) => ({
        width: 32,
        height: 32,
        borderRadius: '50%',
        background: color,
        color: '#fff',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 13,
        fontWeight: 700,
        position: 'relative',
        border: `2px solid ${isOnline ? '#4caf50' : '#666'}`,
        opacity: isOnline ? 1 : 0.5,
    }),
    onlineDot: {
        position: 'absolute',
        bottom: -1,
        right: -1,
        width: 10,
        height: 10,
        borderRadius: '50%',
        background: '#4caf50',
        border: '2px solid #1a1a2e',
    },
    conflictBanner: {
        background: '#ff9800',
        color: '#fff',
        padding: '6px 20px',
        fontSize: 13,
        fontWeight: 600,
        textAlign: 'center',
        animation: 'conflictPulse 1s ease-in-out',
    },
    editorArea: {
        flex: 1,
        position: 'relative',
        overflow: 'auto',
        padding: 20,
    },
    textarea: {
        width: '100%',
        height: '100%',
        padding: 16,
        fontSize: 15,
        lineHeight: 1.6,
        fontFamily: '"SF Mono", "Fira Code", Consolas, monospace',
        border: '1px solid #ddd',
        borderRadius: 8,
        resize: 'none',
        outline: 'none',
        background: '#fff',
        boxSizing: 'border-box',
        boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
    },
    cursorOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        pointerEvents: 'none',
        overflow: 'hidden',
    },
    remoteCursor: (color, top, left) => ({
        position: 'absolute',
        top,
        left,
        width: 2,
        height: 20,
        background: color,
        transition: 'top 0.3s ease-out, left 0.3s ease-out',
        zIndex: 10,
    }),
    cursorLabel: (color) => ({
        position: 'absolute',
        top: -18,
        left: -2,
        background: color,
        color: '#fff',
        fontSize: 10,
        fontWeight: 600,
        padding: '1px 6px',
        borderRadius: '3px 3px 3px 0',
        whiteSpace: 'nowrap',
    }),
    sidebar: {
        width: 280,
        background: '#fff',
        borderLeft: '1px solid #e0e0e0',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
    },
    sidebarHeader: {
        padding: '14px 16px',
        fontSize: 13,
        fontWeight: 700,
        textTransform: 'uppercase',
        letterSpacing: 1,
        color: '#888',
        borderBottom: '1px solid #eee',
    },
    historyList: {
        flex: 1,
        overflowY: 'auto',
        padding: 0,
    },
    historyItem: {
        padding: '10px 16px',
        borderBottom: '1px solid #f0f0f0',
        fontSize: 13,
    },
    historyUser: (color) => ({
        fontWeight: 600,
        color,
        marginRight: 4,
    }),
    historyAction: {
        color: '#666',
    },
    historyText: {
        fontFamily: 'monospace',
        background: '#f5f5f5',
        padding: '1px 4px',
        borderRadius: 3,
        fontSize: 12,
        color: '#333',
    },
    historyTime: {
        fontSize: 11,
        color: '#bbb',
        marginTop: 2,
    },
    docStats: {
        padding: '8px 16px',
        borderTop: '1px solid #eee',
        fontSize: 12,
        color: '#999',
        background: '#fafafa',
    },
};
const globalStyle = `
body { margin: 0; }
@keyframes conflictPulse {
  0% { opacity: 0; transform: translateY(-100%); }
  20% { opacity: 1; transform: translateY(0); }
  80% { opacity: 1; }
  100% { opacity: 0; }
}
`;
// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function getUserColor(userId) {
    return allUsers.find(u => u.id === userId)?.color ?? '#999';
}
function timeAgo(ts) {
    const diff = Math.floor((Date.now() - ts) / 1000);
    if (diff < 5)
        return 'just now';
    if (diff < 60)
        return `${diff}s ago`;
    return `${Math.floor(diff / 60)}m ago`;
}
// ---------------------------------------------------------------------------
// Components
// ---------------------------------------------------------------------------
function PresenceIndicators() {
    const users = useSignal(activeUsers);
    return (_jsx("div", { style: styles.presenceRow, children: users.map(user => (_jsxs("div", { style: styles.avatar(user.color, true), title: user.name, children: [user.avatar, _jsx("div", { style: styles.onlineDot })] }, user.id))) }));
}
function ConflictBanner() {
    const conflict = useSignal(hasConflict);
    if (!conflict)
        return null;
    return (_jsx("div", { style: styles.conflictBanner, children: "Edit conflict detected near your cursor -- auto-resolving..." }));
}
function Editor() {
    const emit = useEmit();
    const doc = useSignal(docSignal);
    const cursorMap = useSignal(cursors);
    const textareaRef = useRef(null);
    const handleInput = useCallback((e) => {
        const textarea = e.currentTarget;
        const newValue = textarea.value;
        const cursorPos = textarea.selectionStart;
        const oldValue = doc;
        if (newValue.length > oldValue.length) {
            // Insert
            const insertedLen = newValue.length - oldValue.length;
            const insertPos = cursorPos - insertedLen;
            const insertedText = newValue.slice(insertPos, cursorPos);
            emit(LocalEdit, { pos: insertPos, text: insertedText, type: 'insert' });
        }
        else if (newValue.length < oldValue.length) {
            // Delete
            const deletedLen = oldValue.length - newValue.length;
            const deletePos = cursorPos + deletedLen;
            const deletedText = oldValue.slice(cursorPos, deletePos);
            emit(LocalEdit, { pos: deletePos, text: deletedText, type: 'delete' });
        }
    }, [doc, emit]);
    const handleSelect = useCallback(() => {
        if (textareaRef.current) {
            const pos = textareaRef.current.selectionStart;
            emit(CursorMoved, { user: 'local', pos });
            const target = cursorSpringTargets.get('local');
            if (target)
                target._set(pos);
        }
    }, [emit]);
    // Calculate approximate cursor positions for remote users
    const remoteCursors = allUsers
        .filter(u => u.id !== 'local')
        .map(user => {
        const pos = cursorMap.get(user.id) ?? 0;
        // Approximate position: ~8px per char, ~20px per line
        const textBefore = doc.slice(0, pos);
        const lines = textBefore.split('\n');
        const lineNum = lines.length - 1;
        const colNum = lines[lines.length - 1]?.length ?? 0;
        const top = 20 + lineNum * 24 + 16;
        const left = 20 + colNum * 8.4 + 16;
        return { user, top, left };
    });
    return (_jsxs("div", { style: styles.editorArea, children: [_jsx("textarea", { ref: textareaRef, style: styles.textarea, value: doc, onChange: handleInput, onSelect: handleSelect, spellCheck: false }), _jsx("div", { style: styles.cursorOverlay, children: remoteCursors.map(({ user, top, left }) => (_jsx("div", { style: styles.remoteCursor(user.color, top, left), children: _jsx("div", { style: styles.cursorLabel(user.color), children: user.name }) }, user.id))) })] }));
}
function HistoryPanel() {
    const history = useSignal(editHistory);
    const doc = useSignal(docSignal);
    return (_jsxs("div", { style: styles.sidebar, children: [_jsx("div", { style: styles.sidebarHeader, children: "Edit History" }), _jsx("div", { style: styles.historyList, children: history.length === 0 ? (_jsx("div", { style: { padding: 16, color: '#bbb', fontSize: 13 }, children: "No edits yet. Start typing!" })) : (history.map((entry) => (_jsxs("div", { style: styles.historyItem, children: [_jsxs("div", { children: [_jsx("span", { style: styles.historyUser(getUserColor(allUsers.find(u => u.name === entry.user)?.id ?? 'local')), children: entry.user }), _jsx("span", { style: styles.historyAction, children: entry.type === 'insert' ? ' inserted ' : ' deleted ' }), _jsx("span", { style: styles.historyText, children: entry.text.replace(/\n/g, '\\n') })] }), _jsxs("div", { style: styles.historyTime, children: ["at position ", entry.pos, " - ", timeAgo(entry.timestamp)] })] }, entry.id)))) }), _jsxs("div", { style: styles.docStats, children: [doc.length, " characters | ", doc.split('\n').length, " lines"] })] }));
}
// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------
export default function App() {
    return (_jsxs(_Fragment, { children: [_jsx("style", { children: globalStyle }), _jsxs("div", { style: styles.container, children: [_jsxs("div", { style: styles.mainPanel, children: [_jsxs("div", { style: styles.header, children: [_jsx("div", { style: styles.headerTitle, children: "Pulse Collaborative Editor" }), _jsx(PresenceIndicators, {})] }), _jsx(ConflictBanner, {}), _jsx(Editor, {})] }), _jsx(HistoryPanel, {})] })] }));
}

// examples/solid/collaborative-editor/src/App.tsx
import { For, Show, onMount, onCleanup } from 'solid-js'
import { useSignal, useEmit, useSpring } from '@pulse/solid'
import type { Signal, SpringValue } from '@pulse/core'
import { engine } from './engine'

/* ------------------------------------------------------------------ */
/*  Types                                                             */
/* ------------------------------------------------------------------ */

interface Cursor { userId: string; name: string; color: string; x: number; y: number; line: number; col: number }
interface Edit { userId: string; text: string; position: number; timestamp: number; type: 'insert' | 'delete' }

/* ------------------------------------------------------------------ */
/*  Bot config                                                        */
/* ------------------------------------------------------------------ */

const BOTS = [
  { id: 'bot-alice', name: 'Alice', color: '#6c5ce7', phrases: ['Hello world!', 'function foo() {}', 'const x = 42;', '// TODO: fix this', 'return result;'] },
  { id: 'bot-bob', name: 'Bob', color: '#00b894', phrases: ['import React from "react"', 'console.log("debug")', 'if (valid) {', 'export default App', '  await fetch(url)'] },
]

/* ------------------------------------------------------------------ */
/*  Events                                                            */
/* ------------------------------------------------------------------ */

const LocalEdit = engine.event<string>('LocalEdit')
const RemoteEdit = engine.event<Edit>('RemoteEdit')
const CursorMoved = engine.event<Cursor>('CursorMoved')
const SelectionChanged = engine.event<{ line: number; col: number }>('SelectionChanged')

/* ------------------------------------------------------------------ */
/*  State                                                             */
/* ------------------------------------------------------------------ */

const documentText = engine.signal<string>(LocalEdit, '// Collaborative Editor\n// Start typing below...\n\n', (_prev, text) => text)
engine.signalUpdate(documentText, RemoteEdit, (prev, edit) => {
  if (edit.type === 'insert') {
    return prev.slice(0, edit.position) + edit.text + prev.slice(edit.position)
  }
  return prev.slice(0, edit.position) + prev.slice(edit.position + edit.text.length)
})

const cursors = engine.signal<Cursor[]>(CursorMoved, [], (prev, cursor) => {
  const idx = prev.findIndex(c => c.userId === cursor.userId)
  if (idx >= 0) { const next = [...prev]; next[idx] = cursor; return next }
  return [...prev, cursor]
})

const editHistory = engine.signal<Edit[]>(RemoteEdit, [], (prev, edit) => [...prev.slice(-50), edit])
engine.signalUpdate(editHistory, LocalEdit, (prev) => [...prev.slice(-50), { userId: 'local', text: '', position: 0, timestamp: Date.now(), type: 'insert' as const }])

const localCursor = engine.signal<{ line: number; col: number }>(SelectionChanged, { line: 0, col: 0 }, (_prev, pos) => pos)

// Spring cursors for bots
const botCursorXTargets: Signal<number>[] = []
const botCursorYTargets: Signal<number>[] = []
const botCursorXSprings: SpringValue[] = []
const botCursorYSprings: SpringValue[] = []

for (const bot of BOTS) {
  const xt = engine.signal(CursorMoved, 100, (prev, c) => c.userId === bot.id ? c.x : prev)
  const yt = engine.signal(CursorMoved, 100, (prev, c) => c.userId === bot.id ? c.y : prev)
  botCursorXTargets.push(xt)
  botCursorYTargets.push(yt)
  botCursorXSprings.push(engine.spring(xt, { stiffness: 150, damping: 18 }))
  botCursorYSprings.push(engine.spring(yt, { stiffness: 150, damping: 18 }))
}

/* ------------------------------------------------------------------ */
/*  Bot simulation                                                    */
/* ------------------------------------------------------------------ */

function startBotSimulation() {
  const intervals: number[] = []
  BOTS.forEach((bot, idx) => {
    let charIdx = 0
    const interval = setInterval(() => {
      const phrase = bot.phrases[Math.floor(Math.random() * bot.phrases.length)]
      const text = documentText.value
      const lines = text.split('\n')
      const targetLine = Math.min(3 + idx * 2, lines.length)
      let position = 0
      for (let i = 0; i < targetLine && i < lines.length; i++) position += lines[i].length + 1

      const edit: Edit = {
        userId: bot.id,
        text: phrase[charIdx % phrase.length],
        position: Math.min(position + charIdx, text.length),
        timestamp: Date.now(),
        type: 'insert',
      }
      engine.emit(RemoteEdit, edit)

      // Move cursor
      const lineLen = lines[targetLine]?.length ?? 0
      engine.emit(CursorMoved, {
        userId: bot.id, name: bot.name, color: bot.color,
        x: 80 + (charIdx % 40) * 8, y: 60 + targetLine * 22,
        line: targetLine, col: charIdx % 40,
      })

      charIdx++
      if (charIdx > 60) charIdx = 0
    }, 1500 + Math.random() * 2000) as unknown as number
    intervals.push(interval)
  })
  return () => intervals.forEach(clearInterval)
}

/* ------------------------------------------------------------------ */
/*  Components                                                        */
/* ------------------------------------------------------------------ */

function BotCursor(props: { index: number; bot: typeof BOTS[0] }) {
  const x = useSpring(botCursorXSprings[props.index])
  const y = useSpring(botCursorYSprings[props.index])

  return (
    <div style={{
      position: 'absolute', left: `${x()}px`, top: `${y()}px`,
      'pointer-events': 'none', 'z-index': '10', transition: 'opacity 0.3s',
    }}>
      <div style={{
        width: '2px', height: '18px', background: props.bot.color,
        'box-shadow': `0 0 4px ${props.bot.color}`,
      }} />
      <div style={{
        background: props.bot.color, color: '#fff', 'font-size': '10px',
        padding: '1px 6px', 'border-radius': '3px', 'white-space': 'nowrap',
        'margin-top': '2px',
      }}>{props.bot.name}</div>
    </div>
  )
}

function HistoryPanel() {
  const history = useSignal(editHistory)

  return (
    <div style={{
      width: '250px', background: '#fff', 'border-left': '1px solid #e0e0e0',
      padding: '16px', overflow: 'auto',
    }}>
      <h3 style={{ 'font-size': '13px', 'font-weight': '600', color: '#333', 'margin-bottom': '12px', 'text-transform': 'uppercase', 'letter-spacing': '0.5px' }}>
        Edit History
      </h3>
      <For each={history().slice(-20).reverse()}>
        {(edit) => {
          const bot = BOTS.find(b => b.id === edit.userId)
          return (
            <div style={{
              padding: '6px 8px', 'border-left': `2px solid ${bot?.color ?? '#4361ee'}`,
              'margin-bottom': '4px', 'font-size': '11px',
            }}>
              <div style={{ color: bot?.color ?? '#4361ee', 'font-weight': '600' }}>{bot?.name ?? 'You'}</div>
              <div style={{ color: '#666', 'font-family': 'monospace' }}>
                {edit.type === 'insert' ? '+' : '-'} "{edit.text.slice(0, 20)}"
              </div>
              <div style={{ color: '#aaa', 'font-size': '10px' }}>
                {new Date(edit.timestamp).toLocaleTimeString()}
              </div>
            </div>
          )
        }}
      </For>
    </div>
  )
}

export default function App() {
  const emit = useEmit()
  const text = useSignal(documentText)
  const allCursors = useSignal(cursors)

  onMount(() => {
    const cleanup = startBotSimulation()
    onCleanup(cleanup)
  })

  return (
    <div style={{ height: '100vh', display: 'flex', 'flex-direction': 'column', 'font-family': '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif' }}>
      {/* Header */}
      <div style={{ background: '#fff', padding: '12px 24px', 'border-bottom': '1px solid #e0e0e0', display: 'flex', 'align-items': 'center', gap: '16px' }}>
        <h1 style={{ 'font-size': '18px', 'font-weight': '600', color: '#333', margin: '0' }}>Collaborative Editor</h1>
        <div style={{ display: 'flex', gap: '8px' }}>
          <For each={BOTS}>
            {(bot) => (
              <div style={{
                display: 'flex', 'align-items': 'center', gap: '4px', padding: '2px 8px',
                'border-radius': '10px', background: bot.color + '22', 'font-size': '11px', color: bot.color,
              }}>
                <div style={{ width: '6px', height: '6px', 'border-radius': '50%', background: bot.color }} />
                {bot.name}
              </div>
            )}
          </For>
          <div style={{
            display: 'flex', 'align-items': 'center', gap: '4px', padding: '2px 8px',
            'border-radius': '10px', background: '#4361ee22', 'font-size': '11px', color: '#4361ee',
          }}>
            <div style={{ width: '6px', height: '6px', 'border-radius': '50%', background: '#4361ee' }} />
            You
          </div>
        </div>
      </div>

      {/* Editor + History */}
      <div style={{ flex: '1', display: 'flex', overflow: 'hidden' }}>
        {/* Editor area */}
        <div style={{ flex: '1', position: 'relative', background: '#fafafa' }}>
          {/* Line numbers */}
          <div style={{
            position: 'absolute', left: '0', top: '0', bottom: '0', width: '48px',
            background: '#f0f0f0', 'border-right': '1px solid #ddd', padding: '16px 0',
            'font-family': 'Consolas, monospace', 'font-size': '13px', color: '#999',
            'line-height': '22px', 'text-align': 'right', 'padding-right': '12px',
            'user-select': 'none',
          }}>
            <For each={text().split('\n')}>
              {(_, i) => <div>{i() + 1}</div>}
            </For>
          </div>

          {/* Bot cursors */}
          <For each={BOTS}>
            {(bot, i) => <BotCursor index={i()} bot={bot} />}
          </For>

          {/* Textarea */}
          <textarea
            value={text()}
            onInput={(e) => emit(LocalEdit, e.currentTarget.value)}
            onClick={(e) => {
              const ta = e.currentTarget
              const lines = ta.value.slice(0, ta.selectionStart).split('\n')
              emit(SelectionChanged, { line: lines.length - 1, col: lines[lines.length - 1].length })
            }}
            style={{
              position: 'absolute', left: '48px', top: '0', right: '0', bottom: '0',
              padding: '16px', 'font-family': 'Consolas, monospace', 'font-size': '13px',
              'line-height': '22px', border: 'none', background: 'transparent',
              resize: 'none', outline: 'none', color: '#333',
            }}
          />

          {/* Conflict markers overlay */}
          <Show when={allCursors().length > 0}>
            <div style={{
              position: 'absolute', bottom: '8px', left: '56px', 'font-size': '11px', color: '#999',
            }}>
              {allCursors().length} active cursor(s)
            </div>
          </Show>
        </div>

        <HistoryPanel />
      </div>
    </div>
  )
}
