// examples/react-showcase/src/pages/ApiCallPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/api-call/src/engine'
import ApiCallApp from '../../../react/api-call/src/App'

export default function ApiCallPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <ApiCallApp />
    </PulseProvider>
  )
}

// examples/solid-showcase/src/pages/ApiCallPage.tsx
import { onMount, onCleanup } from 'solid-js'
import { PulseProvider } from '@pulse/solid'
import { engine } from '../../../solid/api-call/src/engine'
import ApiCallApp from '../../../solid/api-call/src/App'

export default function ApiCallPage() {
  onMount(() => {
    ;(window as any).__pulseEngine = engine
  })
  onCleanup(() => {
    ;(window as any).__pulseEngine = null
  })

  return (
    <PulseProvider engine={engine}>
      <div class="example-container" style={{ 'min-height': '100%' }}>
        <ApiCallApp />
      </div>
    </PulseProvider>
  )
}
