// examples/react-showcase/src/pages/MorphingGrid3DPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/3d-morphing-grid/src/engine'
import MorphingGrid3DApp from '../../../react/3d-morphing-grid/src/App'

export default function MorphingGrid3DPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <MorphingGrid3DApp />
    </PulseProvider>
  )
}

// examples/solid-showcase/src/pages/MorphingGrid3DPage.tsx
import { onMount, onCleanup } from 'solid-js'
import { PulseProvider } from '@pulse/solid'
import { engine } from '../../../solid/3d-morphing-grid/src/engine'
import App from '../../../solid/3d-morphing-grid/src/App'

export default function MorphingGrid3DPage() {
  onMount(() => {
    ;(window as any).__pulseEngine = engine
  })
  onCleanup(() => {
    ;(window as any).__pulseEngine = null
  })

  return (
    <PulseProvider engine={engine}>
      <div class="example-container" style={{ 'min-height': '100%' }}>
        <App />
      </div>
    </PulseProvider>
  )
}
