// examples/react-showcase/src/pages/NotificationSystemPage.js
import { jsx as _jsx } from "react/jsx-runtime";
import { useEffect } from 'react';
import { PulseProvider } from '@pulse/react';
import { engine } from '../../../react/notification-system/src/engine';
import NotificationSystemApp from '../../../react/notification-system/src/App';
export default function NotificationSystemPage() {
    useEffect(() => {
        ;
        window.__pulseEngine = engine;
        return () => { ; window.__pulseEngine = null; };
    }, []);
    return (_jsx(PulseProvider, { engine: engine, children: _jsx(NotificationSystemApp, {}) }));
}

// examples/solid-showcase/src/pages/NotificationSystemPage.tsx
import { onMount, onCleanup } from 'solid-js'
import { PulseProvider } from '@pulse/solid'
import { engine } from '../../../solid/notification-system/src/engine'
import App from '../../../solid/notification-system/src/App'

export default function NotificationSystemPage() {
  onMount(() => {
    ;(window as any).__pulseEngine = engine
  })
  onCleanup(() => {
    ;(window as any).__pulseEngine = null
  })

  return (
    <PulseProvider engine={engine}>
      <div class="example-container" style={{ 'min-height': '100%' }}>
        <App />
      </div>
    </PulseProvider>
  )
}
