// examples/react-showcase/src/pages/SimpleAnimationPage.js
import { jsx as _jsx } from "react/jsx-runtime";
import { useEffect } from 'react';
import { PulseProvider } from '@pulse/react';
import { engine } from '../../../react/simple-animation/src/engine';
import SimpleAnimationApp from '../../../react/simple-animation/src/App';
export default function SimpleAnimationPage() {
    useEffect(() => {
        ;
        window.__pulseEngine = engine;
        return () => { ; window.__pulseEngine = null; };
    }, []);
    return (_jsx(PulseProvider, { engine: engine, children: _jsx(SimpleAnimationApp, {}) }));
}

// examples/solid-showcase/src/pages/SimpleAnimationPage.tsx
import { onMount, onCleanup } from 'solid-js'
import { PulseProvider } from '@pulse/solid'
import { engine } from '../../../solid/simple-animation/src/engine'
import SimpleAnimationApp from '../../../solid/simple-animation/src/App'

export default function SimpleAnimationPage() {
  onMount(() => {
    ;(window as any).__pulseEngine = engine
  })
  onCleanup(() => {
    ;(window as any).__pulseEngine = null
  })

  return (
    <PulseProvider engine={engine}>
      <div class="example-container" style={{ 'min-height': '100%' }}>
        <SimpleAnimationApp />
      </div>
    </PulseProvider>
  )
}
