// examples/react-showcase/src/pages/TodoListPage.tsx
import { useEffect } from 'react'
import { PulseProvider } from '@pulse/react'
import { engine } from '../../../react/todo-list/src/engine'
import TodoListApp from '../../../react/todo-list/src/App'

export default function TodoListPage() {
  useEffect(() => {
    ;(window as any).__pulseEngine = engine
    return () => { ;(window as any).__pulseEngine = null }
  }, [])

  return (
    <PulseProvider engine={engine}>
      <TodoListApp />
    </PulseProvider>
  )
}

// examples/solid-showcase/src/pages/TodoListPage.tsx
import { onMount, onCleanup } from 'solid-js'
import { PulseProvider } from '@pulse/solid'
import { engine } from '../../../solid/todo-list/src/engine'
import TodoApp from '../../../solid/todo-list/src/App'

export default function TodoListPage() {
  onMount(() => {
    ;(window as any).__pulseEngine = engine
  })
  onCleanup(() => {
    ;(window as any).__pulseEngine = null
  })

  return (
    <PulseProvider engine={engine}>
      <div class="example-container" style={{ 'min-height': '100%' }}>
        <TodoApp />
      </div>
    </PulseProvider>
  )
}
